ft: extend crr stat report for per-site metrics
scality/cloudserver pull request #1308
Opened 2018-06-21 20:45 UTC by alexanderchan-scality

2018-06-21 20:45 UTC, bert-e commented
# Hello alexanderchan-scality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-06-21 20:45 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers

2018-06-21 20:55 UTC, RachedBenMustapha commented
@bert-e wait

2018-06-21 20:59 UTC, rachedbenmustapha requested changes

2018-06-21 20:59 UTC, RachedBenMustapha commented on lib/utilities/reportHandler.js
> +                    // something has gone wrong
Logging the error would be good.

2018-06-21 20:59 UTC, RachedBenMustapha commented on lib/utilities/reportHandler.js
> +        total: done => _crrRequest(backbeatMetrics, details, 'all', done),
This seems to break compatibility with the existing schema where backlog, completions and throughput are inline.

2018-06-22 17:41 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-22 18:09 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-22 18:17 UTC, rachedbenmustapha requested changes

2018-06-22 18:17 UTC, RachedBenMustapha commented on lib/utilities/reportHandler.js
> +                            method: 'getCRRStats',
The error itself should include what made the code bail, in this case the error and the side. Otherwise things are very difficult to troubleshoot.

2018-06-22 18:27 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-22 18:28 UTC, ironman-machine commented
PR has been updated. Reviewers, please be cautious.

2018-06-22 21:52 UTC, rachedbenmustapha requested changes

2018-06-22 21:52 UTC, RachedBenMustapha commented on lib/utilities/reportHandler.js
> +                        log.debug('err should be null', {
message should be more explicit (like failed to get site-specific crr stats) and include the site in the extra properties

2018-06-22 23:34 UTC, rachedbenmustapha approved these changes

2018-06-26 23:12 UTC, nicolas2bert approved these changes
Should we have tests for these changes? Are they coming later?

2018-06-27 04:51 UTC, RachedBenMustapha commented on lib/utilities/reportHandler.js
> -    const { replicationEndpoints, localCache: redis } = config;
@rahulreddy can you confirm that it's expected that CRR stats are only found in the persistent redis/sentinel cluster?

2018-06-27 04:52 UTC, RachedBenMustapha commented on lib/utilities/reportHandler.js
> -    const { replicationEndpoints, localCache: redis } = config;
@jonathan-gramain could also weigh in

2018-06-29 19:11 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.0`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-06-29 19:30 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.0`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`



Please check the status of the associated issue ZENKO-572.

Goodbye alexanderchan-scality.

2018-06-29 19:30 UTC, merged