Feature/zenko 267 md ingestion routes
scality/cloudserver pull request #1309
Opened 2018-06-21 21:34 UTC by JianqinWang

Dependent on https://github.com/scality/bucketclient/pull/139

2018-06-22 22:01 UTC, jonathan-gramain requested changes

2018-06-22 22:01 UTC, jonathan-gramain commented on lib/routes/routeMetadata.js
> +- getting list of objects for each bucket -
minor: comments are inverted between lines 47 and 49

2018-06-22 22:01 UTC, jonathan-gramain commented on lib/routes/routeMetadata.js
> +    const useMultipleBackend = request.resourceType === 'multiplebackenddata';
This is specific to backbeat routes, please remove

2018-06-22 22:01 UTC, jonathan-gramain commented on lib/routes/routeMetadata.js
> +    const requestContexts = prepareRequestContexts('objectReplicate', request);
Feels weird to use `objectReplicate` as a context here, which is also technical debt for backbeat (as backbeat does more than just replicating an object). But there may be implications with Vault too, I don't remember exactly, so it's possible that it is quicker to stick with this context.

If you have time to find out, can you add a comment?

2018-06-26 18:27 UTC, jonathan-gramain approved these changes

2018-06-26 18:27 UTC, jonathan-gramain commented on lib/routes/routeMetadata.js
> +GET /_/metadata/listbuckets/<raft session id>
Just thinking it could be nice to be able to use these routes in the future as an internal mongodb frontend for other purposes (e.g. listbuckets may be used by lifecycle extension to avoid reading from the log and maintaining a list of buckets on zookeeper). Not that this is the point of implementing anything here but thinking if we could also use the routes in a similar way with a mongodb backend later that would be neat!

2018-06-26 21:14 UTC, tmacro approved these changes

2018-06-27 16:46 UTC, bennettbuchanan approved these changes
Nice! 🚢

2018-06-27 16:46 UTC, bennettbuchanan commented on lib/routes/routeMetadata.js
> +// const metadata = require('../metadata/wrapper');
Extra comment 😃

2018-06-28 00:26 UTC, bert-e commented
# Hello JianqinWang,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-06-28 00:26 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.0/feature/ZENKO-267-MD-Ingestion-Routes` with contents from `feature/ZENKO-267-MD-Ingestion-Routes`
and `development/8.0`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```
#!bash
 $ git fetch
 $ git checkout -B w/8.0/feature/ZENKO-267-MD-Ingestion-Routes origin/development/8.0
 $ git merge origin/feature/ZENKO-267-MD-Ingestion-Routes
 $ # <intense conflict resolution>
 $ git push -u origin w/8.0/feature/ZENKO-267-MD-Ingestion-Routes
```

2018-06-30 20:24 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `feature/ZENKO-267-MD-Ingestion-Routes` into
`development/7.4`
* [w/8.0/feature/ZENKO-267-MD-Ingestion-Routes](https://github.com/scality/s3/compare/development/8.0...w/8.0/feature/ZENKO-267-MD-Ingestion-Routes) will be merged into `development/8.0` (pull request #1343)



The following branches will **NOT** be impacted:

* `development/6.4`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2018-06-30 20:39 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/7.4`

* :heavy_check_mark: `development/8.0`



The following branches will **NOT** be impacted:

* `development/6.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-06-30 21:36 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/7.4`

* :heavy_check_mark: `development/8.0`



The following branches have **NOT** changed:

* `development/6.4`



Please check the status of the associated issue ZENKO-267.

Goodbye JianqinWang.

2018-06-30 21:36 UTC, merged