feature: ZENKO-382 skip version for nfs exported bucket
scality/cloudserver pull request #1337
Opened 2018-06-29 23:20 UTC by rahulreddy

2018-06-29 23:20 UTC, bert-e commented
# Hello rahulreddy,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-06-29 23:20 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers

2018-06-29 23:21 UTC, rahulreddy commented
Sorry no tests due to urgency of the PR

2018-06-29 23:21 UTC, rahulreddy commented
@bert-e wait

2018-06-29 23:24 UTC, ploki approved these changes

2018-06-30 09:41 UTC, rahulreddy commented
@bert-e help

2018-06-30 09:41 UTC, bert-e commented
# Help page



The following options and commands are available at this time.

## Options ##


name   | description  | privileged
------ | ------------ | ------------
:arrow_right: **create_pull_requests** | Allow the creation of integration pull requests. | 
:arrow_right: **bypass_author_approval** | Bypass the pull request author's approval |  :star: 
:arrow_right: **bypass_tester_approval** | Bypass the pull request testers' approval |  :star: 
:arrow_right: **bypass_jira_check** | Bypass the Jira issue check |  :star: 
:arrow_right: **unanimity** | Change review acceptance criteria from `one reviewer at least` to `all reviewers` | 
:arrow_right: **bypass_commit_size** | Bypass the check on the size of the changeset ```TBA``` |  :star: 
:arrow_right: **bypass_build_status** | Bypass the build and test status |  :star: 
:arrow_right: **bypass_peer_approval** | Bypass the pull request peers' approval |  :star: 
:arrow_right: **after_pull_request** | Wait for the given pull request id to be merged before continuing with the current one. | 
:arrow_right: **wait** | Instruct Bert-E not to run until further notice. | 
:arrow_right: **bypass_incompatible_branch** | Bypass the check on the source branch prefix |  :star: 
:arrow_right: **no_octopus** | Prevent Wall-E from doing any octopus merge and use multiple consecutive merge instead | 



## Commands ##


name   | description  | privileged
------ | ------------ | ------------
:arrow_right: **build** | Re-start a fresh build ```TBA``` | 
:arrow_right: **force_reset** | Delete integration branches & pull requests, and restart merge process from the beginning. | 
:arrow_right: **retry** | Re-start a fresh build ```TBA``` | 
:arrow_right: **help** | Print Bert-E's manual in the pull request. | 
:arrow_right: **reset** | Try to remove integration branches unless there are commits on them which do not appear on the source branch. | 
:arrow_right: **clear** | Remove all comments from Bert-E from the history ```TBA``` | 
:arrow_right: **status** | Print Bert-E's current status in the pull request ```TBA``` |

2018-06-30 09:41 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers

2018-06-30 09:42 UTC, rahulreddy commented
@bert-e bypass_peer_approval

2018-06-30 09:42 UTC, bert-e commented
# Not authorized



I'm afraid I cannot do that, @rahulreddy:

> @bert-e bypass_peer_approval


You cannot use `bypass_peer_approval` in your own pull request.


Please **edit** or **delete** the corresponding comment so I can move on.

2018-06-30 09:42 UTC, rahulreddy commented
@bert-e bypass_author_approval

2018-06-30 09:49 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers

2018-06-30 18:01 UTC, jonathan-gramain requested changes

2018-06-30 18:01 UTC, jonathan-gramain commented on lib/api/bucketPutVersioning.js
> +            return(null, corsHeaders);
I think you forgot `callback(...)`

2018-06-30 18:51 UTC, jonathan-gramain approved these changes

2018-06-30 18:51 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.0`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-06-30 19:10 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.0`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`



Please check the status of the associated issue ZENKO-610.

Goodbye rahulreddy.

2018-06-30 19:10 UTC, merged