ft: Add storage quota config
scality/cloudserver pull request #1356
Opened 2018-07-06 21:57 UTC by ssalaues

Allows for storage quota configuration to be enabled from docker entry point.

2018-07-06 21:57 UTC, bert-e commented
# Hello ssalaues,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-07-06 21:57 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers

2018-07-06 22:02 UTC, dora-korpar approved these changes

2018-07-06 22:13 UTC, giacope approved these changes

2018-07-06 22:15 UTC, bennettbuchanan commented on docker-entrypoint.sh
> +if [[ "$STORAGE_QUOTA_ENABLED" ]]; then
Why not set `utapi.metrics` with the metrics array value as `['location']`? That way we can extend it later for the other metric granularities.

2018-07-06 22:17 UTC, jonathan-gramain requested changes

2018-07-06 22:17 UTC, jonathan-gramain commented on docker-entrypoint.sh
> +if [[ "$STORAGE_QUOTA_ENABLED" ]]; then
Can you change the name to `STORAGE_LIMIT_ENABLED`? It is the official name of the feature and will avoid confusion with the upcoming quotas support (per user).

2018-07-06 22:17 UTC, bennettbuchanan requested changes

2018-07-06 22:17 UTC, bennettbuchanan commented on docker-entrypoint.sh
> +if [[ "$STORAGE_QUOTA_ENABLED" ]]; then
Seems like we may eventually want to introduce other metrics.

2018-07-06 22:17 UTC, jonathan-gramain commented
@bert-e wait

2018-07-06 23:12 UTC, ssalaues commented
Updated PR to accommodate the requested changes.

2018-07-06 23:22 UTC, jonathan-gramain approved these changes

2018-07-06 23:38 UTC, bennettbuchanan approved these changes

2018-07-06 23:42 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.0`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-07-09 13:58 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.0`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`



Please check the status of the associated issue ZENKO-679.

Goodbye ssalaues.

2018-07-09 13:58 UTC, merged