bf: ZENKO-1013 use backbeat api metrics routes for stats
scality/cloudserver pull request #1490
Opened 2018-08-20 18:55 UTC by alexanderchan-scality

change `backbeat` metrics methods from reading from `redis` directly to making request to `backbeatAPI`

2018-08-20 18:55 UTC, bert-e commented
# Hello alexanderchan-scality,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-08-20 18:55 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/ZENKO-1013/useBackbeatApiMetrics` into
`development/8.0`
* [w/8.1/bugfix/ZENKO-1013/useBackbeatApiMetrics](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/ZENKO-1013/useBackbeatApiMetrics) will be merged into `development/8.1` (pull request #1491)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2018-08-20 18:55 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rahulreddy

* @dora-korpar

* @RachedBenMustapha

2018-08-20 18:56 UTC, alexanderchan-scality commented
@bert-e wait

2018-08-23 22:38 UTC, philipyoo approved these changes

2018-08-23 22:50 UTC, dora-korpar approved these changes

2018-08-23 22:57 UTC, rahulreddy requested changes

2018-08-23 22:57 UTC, rahulreddy commented on tests/functional/utilities/reportHandler.js
> +        it('should return correct', done => {
`it should return location metrics`?

2018-08-23 23:17 UTC, tmacro approved these changes

2018-08-23 23:44 UTC, rahulreddy approved these changes

2018-08-23 23:46 UTC, bert-e commented
# History mismatch



Merge commit #49aa27a794f472b5ca00ac015018f311651fa35d on the integration branch
`w/8.1/bugfix/ZENKO-1013/useBackbeatApiMetrics` is merging a branch which is neither the current
branch `bugfix/ZENKO-1013/useBackbeatApiMetrics` nor the development branch
`development/8.1`.

It is likely due to a rebase of the branch `bugfix/ZENKO-1013/useBackbeatApiMetrics` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2018-08-23 23:46 UTC, rahulreddy commented
@bert-e reset

2018-08-23 23:46 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2018-08-23 23:46 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/ZENKO-1013/useBackbeatApiMetrics` into
`development/8.0`
* [w/8.1/bugfix/ZENKO-1013/useBackbeatApiMetrics](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/ZENKO-1013/useBackbeatApiMetrics) will be merged into `development/8.1` (pull request #1508)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2018-08-24 00:14 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.0`

* :heavy_check_mark: `development/8.1`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-08-24 00:57 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.0`

* :heavy_check_mark: `development/8.1`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`



Please check the status of the associated issue ZENKO-1013.

Goodbye alexanderchan-scality.

2018-08-24 00:57 UTC, merged