FX: ZENKO-1112 Management client error logging
scality/cloudserver pull request #1528
Opened 2018-09-05 20:51 UTC by nicolas2bert

2018-09-05 20:51 UTC, bert-e commented
# Hello nicolas2bert,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get
information on this process.





*Status report is not available.*

2018-09-05 20:51 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.1/bugfix/ZENKO-1112/log` with contents from `bugfix/ZENKO-1112/log`
and `development/8.1`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.1/bugfix/ZENKO-1112/log origin/development/8.1
 $ git merge origin/bugfix/ZENKO-1112/log
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.1/bugfix/ZENKO-1112/log
```

2018-09-05 22:06 UTC, bert-e commented
# Conflict




A conflict has been raised during the update of
integration branch `w/8.1/bugfix/ZENKO-1112/log` with contents from `bugfix/ZENKO-1112/log`
and `development/8.1`.

Please resolve the conflict on **the integration branch** (`w/8.1/bugfix/ZENKO-1112/log`).


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout w/8.1/bugfix/ZENKO-1112/log
 $ git pull  # or "git reset --hard origin/w/8.1/bugfix/ZENKO-1112/log"
 $ git merge origin/development/8.1
 $ # <intense conflict resolution>
 $ git commit
 $ git merge origin/bugfix/ZENKO-1112/log
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.1/bugfix/ZENKO-1112/log
```

2018-09-05 22:26 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/ZENKO-1112/log` into
`development/8.0`
* [w/8.1/bugfix/ZENKO-1112/log](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/ZENKO-1112/log) will be merged into `development/8.1` (pull request #1529)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2018-09-05 22:26 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rahulreddy

* @dora-korpar

* @RachedBenMustapha

2018-09-05 22:37 UTC, bert-e commented
# History mismatch



Merge commit #c2fa829c7fdd8c1da59e1ca0f9e491f707231c56 on the integration branch
`w/8.1/bugfix/ZENKO-1112/log` is merging a branch which is neither the current
branch `bugfix/ZENKO-1112/log` nor the development branch
`development/8.1`.

It is likely due to a rebase of the branch `bugfix/ZENKO-1112/log` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2018-09-05 22:40 UTC, nicolas2bert commented
@bert-e help

2018-09-05 22:40 UTC, bert-e commented
# Help page



The following options and commands are available at this time.

## Options ##


name   | description  | privileged
------ | ------------ | ------------
:arrow_right: **bypass_author_approval** | Bypass the pull request author's approval |  :star: 
:arrow_right: **bypass_peer_approval** | Bypass the pull request peers' approval |  :star: 
:arrow_right: **wait** | Instruct Bert-E not to run until further notice. | 
:arrow_right: **no_octopus** | Prevent Wall-E from doing any octopus merge and use multiple consecutive merge instead | 
:arrow_right: **unanimity** | Change review acceptance criteria from `one reviewer at least` to `all reviewers` | 
:arrow_right: **bypass_jira_check** | Bypass the Jira issue check |  :star: 
:arrow_right: **after_pull_request** | Wait for the given pull request id to be merged before continuing with the current one. | 
:arrow_right: **bypass_commit_size** | Bypass the check on the size of the changeset ```TBA``` |  :star: 
:arrow_right: **bypass_leader_approval** | Bypass the pull request leaders' approval |  :star: 
:arrow_right: **bypass_incompatible_branch** | Bypass the check on the source branch prefix |  :star: 
:arrow_right: **bypass_build_status** | Bypass the build and test status |  :star: 
:arrow_right: **create_pull_requests** | Allow the creation of integration pull requests. | 



## Commands ##


name   | description  | privileged
------ | ------------ | ------------
:arrow_right: **retry** | Re-start a fresh build ```TBA``` | 
:arrow_right: **status** | Print Bert-E's current status in the pull request ```TBA``` | 
:arrow_right: **force_reset** | Delete integration branches & pull requests, and restart merge process from the beginning. | 
:arrow_right: **clear** | Remove all comments from Bert-E from the history ```TBA``` | 
:arrow_right: **reset** | Try to remove integration branches unless there are commits on them which do not appear on the source branch. | 
:arrow_right: **help** | Print Bert-E's manual in the pull request. | 
:arrow_right: **build** | Re-start a fresh build ```TBA``` |

2018-09-05 22:40 UTC, bert-e commented
# History mismatch



Merge commit #c2fa829c7fdd8c1da59e1ca0f9e491f707231c56 on the integration branch
`w/8.1/bugfix/ZENKO-1112/log` is merging a branch which is neither the current
branch `bugfix/ZENKO-1112/log` nor the development branch
`development/8.1`.

It is likely due to a rebase of the branch `bugfix/ZENKO-1112/log` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2018-09-05 22:40 UTC, nicolas2bert commented
@bert-e reset

2018-09-05 22:40 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2018-09-05 22:40 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.1/bugfix/ZENKO-1112/log` with contents from `bugfix/ZENKO-1112/log`
and `development/8.1`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.1/bugfix/ZENKO-1112/log origin/development/8.1
 $ git merge origin/bugfix/ZENKO-1112/log
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.1/bugfix/ZENKO-1112/log
```

2018-09-05 22:57 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/ZENKO-1112/log` into
`development/8.0`
* [w/8.1/bugfix/ZENKO-1112/log](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/ZENKO-1112/log) will be merged into `development/8.1` (pull request #1530)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2018-09-05 22:57 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:



* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rahulreddy

* @dora-korpar

* @RachedBenMustapha

2018-09-06 00:58 UTC, bert-e commented
# History mismatch



Merge commit #48b4df82050eaf1362aac2300b24c265751a608f on the integration branch
`w/8.1/bugfix/ZENKO-1112/log` is merging a branch which is neither the current
branch `bugfix/ZENKO-1112/log` nor the development branch
`development/8.1`.

It is likely due to a rebase of the branch `bugfix/ZENKO-1112/log` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2018-09-06 23:43 UTC, rachedbenmustapha requested changes
I think we should reshape these errors as well in the top-level logs from initManagement, as well as the apply overlay/save overlay functions.

2018-09-10 18:31 UTC, tmacro approved these changes

2018-09-10 18:38 UTC, jeremyds reviewed
Except my comment, the rest lgtm

2018-09-10 18:38 UTC, jeremyds commented on lib/management/push.js
> +            logger.error(`management client error: ${errorMessage}`,
no need to reshape here?

2018-09-10 18:46 UTC, JianqinWang approved these changes

2018-09-10 20:49 UTC, rachedbenmustapha approved these changes

2018-09-10 20:53 UTC, rahulreddy commented
@bert-e reset

2018-09-10 20:53 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2018-09-10 20:53 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.1/bugfix/ZENKO-1112/log` with contents from `bugfix/ZENKO-1112/log`
and `development/8.1`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.1/bugfix/ZENKO-1112/log origin/development/8.1
 $ git merge origin/bugfix/ZENKO-1112/log
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.1/bugfix/ZENKO-1112/log
```

2018-09-10 21:30 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/ZENKO-1112/log` into
`development/8.0`
* [w/8.1/bugfix/ZENKO-1112/log](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/ZENKO-1112/log) will be merged into `development/8.1` (pull request #1539)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2018-09-10 21:39 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.0`

* :heavy_check_mark: `development/8.1`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of Release Engineering will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of Release Engineering now.

2018-09-10 21:39 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.0`

* :heavy_check_mark: `development/8.1`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`



Please check the status of the associated issue ZENKO-1112.

Goodbye nicolas2bert.

2018-09-10 21:39 UTC, merged