bugfix: S3C-2274 Fail to exit process before startup
scality/cloudserver pull request #1947
Opened 2019-06-19 21:33 UTC by nicolas2bert

2019-06-19 21:33 UTC, bert-e commented
# Hello nicolas2bert,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/cloudserver/bert-e/doc/user).





*Status report is not available.*

2019-06-19 21:33 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-2274/exit-process` into
`development/6.4`
* [w/7.4/bugfix/S3C-2274/exit-process](https://github.com/scality/cloudserver/compare/development/7.4...w/7.4/bugfix/S3C-2274/exit-process) will be merged into `development/7.4` (pull request #1948)
* [w/7.5/bugfix/S3C-2274/exit-process](https://github.com/scality/cloudserver/compare/development/7.5...w/7.5/bugfix/S3C-2274/exit-process) will be merged into `development/7.5` (pull request #1949)
* [w/8.0/bugfix/S3C-2274/exit-process](https://github.com/scality/cloudserver/compare/development/8.0...w/8.0/bugfix/S3C-2274/exit-process) will be merged into `development/8.0` (pull request #1950)
* [w/8.1/bugfix/S3C-2274/exit-process](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/S3C-2274/exit-process) will be merged into `development/8.1` (pull request #1951)





*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2019-06-19 21:33 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rahulreddy

* @dora-korpar

* @rachedbenmustapha

2019-06-19 22:24 UTC, rahulreddy approved these changes

2019-06-19 22:35 UTC, rachedbenmustapha requested changes

2019-06-19 22:35 UTC, RachedBenMustapha commented on lib/server.js
> +        process.exit(0);
This should be in an `else`, otherwise if there is a server attribute, the shutdown will not be graceful (what the callback is for).

2019-06-19 22:35 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rahulreddy

* @dora-korpar

* @rachedbenmustapha





The following reviewers are expecting changes from the author, or must review again:

* @rachedbenmustapha

2019-06-19 22:50 UTC, bert-e commented
# History mismatch



Merge commit #85f8b73709975c62c9472faab4fe8607c2288781 on the integration branch
`w/7.4/bugfix/S3C-2274/exit-process` is merging a branch which is neither the current
branch `bugfix/S3C-2274/exit-process` nor the development branch
`development/7.4`.

It is likely due to a rebase of the branch `bugfix/S3C-2274/exit-process` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-06-19 23:14 UTC, nicolas2bert commented
@bert-e help

2019-06-19 23:14 UTC, bert-e commented
# Help page



The following options and commands are available at this time.

## Options ##


name   | description  | privileged   | authored
------ | ------------ | ------------ |----------
:arrow_right: **wait** | Instruct Bert-E not to run until further notice. |  | 
:arrow_right: **bypass_peer_approval** | Bypass the pull request peers' approval |  :star:  | 
:arrow_right: **no_octopus** | Prevent Wall-E from doing any octopus merge and use multiple consecutive merge instead |  | 
:arrow_right: **create_pull_requests** | Allow the creation of integration pull requests. |  | 
:arrow_right: **bypass_build_status** | Bypass the build and test status |  :star:  | 
:arrow_right: **approve** | Instruct Bert-E that the author has approved the pull request. |  |  :writing_hand: 
:arrow_right: **after_pull_request** | Wait for the given pull request id to be merged before continuing with the current one. |  | 
:arrow_right: **bypass_incompatible_branch** | Bypass the check on the source branch prefix |  :star:  | 
:arrow_right: **bypass_jira_check** | Bypass the Jira issue check |  :star:  | 
:arrow_right: **bypass_commit_size** | Bypass the check on the size of the changeset ```TBA``` |  :star:  | 
:arrow_right: **unanimity** | Change review acceptance criteria from `one reviewer at least` to `all reviewers` |  | 
:arrow_right: **bypass_author_approval** | Bypass the pull request author's approval |  :star:  | 
:arrow_right: **bypass_leader_approval** | Bypass the pull request leaders' approval |  :star:  | 



## Commands ##


name   | description  | privileged
------ | ------------ | ------------
:arrow_right: **help** | Print Bert-E's manual in the pull request. | 
:arrow_right: **status** | Print Bert-E's current status in the pull request ```TBA``` | 
:arrow_right: **build** | Re-start a fresh build ```TBA``` | 
:arrow_right: **reset** | Try to remove integration branches unless there are commits on them which do not appear on the source branch. | 
:arrow_right: **clear** | Remove all comments from Bert-E from the history ```TBA``` | 
:arrow_right: **retry** | Re-start a fresh build ```TBA``` | 
:arrow_right: **force_reset** | Delete integration branches & pull requests, and restart merge process from the beginning. |

2019-06-19 23:14 UTC, bert-e commented
# History mismatch



Merge commit #85f8b73709975c62c9472faab4fe8607c2288781 on the integration branch
`w/7.4/bugfix/S3C-2274/exit-process` is merging a branch which is neither the current
branch `bugfix/S3C-2274/exit-process` nor the development branch
`development/7.4`.

It is likely due to a rebase of the branch `bugfix/S3C-2274/exit-process` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2019-06-19 23:14 UTC, nicolas2bert commented
@bert-e reset

2019-06-19 23:14 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2019-06-19 23:14 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-2274/exit-process` into
`development/6.4`
* [w/7.4/bugfix/S3C-2274/exit-process](https://github.com/scality/cloudserver/compare/development/7.4...w/7.4/bugfix/S3C-2274/exit-process) will be merged into `development/7.4` (pull request #1952)
* [w/7.5/bugfix/S3C-2274/exit-process](https://github.com/scality/cloudserver/compare/development/7.5...w/7.5/bugfix/S3C-2274/exit-process) will be merged into `development/7.5` (pull request #1953)
* [w/8.0/bugfix/S3C-2274/exit-process](https://github.com/scality/cloudserver/compare/development/8.0...w/8.0/bugfix/S3C-2274/exit-process) will be merged into `development/8.0` (pull request #1954)
* [w/8.1/bugfix/S3C-2274/exit-process](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/S3C-2274/exit-process) will be merged into `development/8.1` (pull request #1955)





*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2019-06-19 23:14 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rahulreddy

* @dora-korpar

* @rachedbenmustapha





The following reviewers are expecting changes from the author, or must review again:

* @rachedbenmustapha

2019-06-19 23:38 UTC, rachedbenmustapha approved these changes

2019-06-19 23:38 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rahulreddy

* @dora-korpar

* @rachedbenmustapha

2019-07-09 20:44 UTC, rahulreddy approved these changes

2019-07-10 16:32 UTC, nicolas2bert commented
@bert-e approve

2019-07-10 16:32 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/920dbd87521ce7f6455f264ab5cf4aa88a641d22) did not succeed in branch w/7.5/bugfix/S3C-2274/exit-process.




*The following options are set:* **approve**

2019-08-26 18:05 UTC, nicolas2bert commented
@bert-e approve

2019-08-26 18:07 UTC, bert-e commented
# History mismatch



Merge commit #f8592929d7dba1976fbd10b485f111381e18b599 on the integration branch
`w/7.4/bugfix/S3C-2274/exit-process` is merging a branch which is neither the current
branch `bugfix/S3C-2274/exit-process` nor the development branch
`development/7.4`.

It is likely due to a rebase of the branch `bugfix/S3C-2274/exit-process` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2019-08-26 20:20 UTC, bert-e commented
# History mismatch



Merge commit #f8592929d7dba1976fbd10b485f111381e18b599 on the integration branch
`w/7.5/bugfix/S3C-2274/exit-process` is merging a branch which is neither the current
branch `bugfix/S3C-2274/exit-process` nor the development branch
`development/7.5`.

It is likely due to a rebase of the branch `bugfix/S3C-2274/exit-process` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2019-08-26 20:43 UTC, nicolas2bert commented
@bert-e reset

2019-08-26 20:43 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-08-26 20:44 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-2274/exit-process` into
`development/7.4`
* [w/7.5/bugfix/S3C-2274/exit-process](https://github.com/scality/cloudserver/compare/development/7.5...w/7.5/bugfix/S3C-2274/exit-process) will be merged into `development/7.5` (pull request #2094)
* [w/8.1/bugfix/S3C-2274/exit-process](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/S3C-2274/exit-process) will be merged into `development/8.1` (pull request #2095)



The following branches will **NOT** be impacted:

* `development/6.4`
* `stabilization/7.5.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.







*The following options are set:* **approve**

2019-08-26 20:45 UTC, nicolas2bert commented
@bert-e approve

2019-08-26 20:56 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/86b689653c3395619e6e82289917ea14da19299c) did not succeed in branch w/8.1/bugfix/S3C-2274/exit-process.




*The following options are set:* **approve**

2019-08-26 21:30 UTC, nicolas2bert commented
@bert-e approve

2019-08-27 15:44 UTC, nicolas2bert commented
@bert-e reset

2019-08-27 15:44 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-08-27 15:45 UTC, nicolas2bert commented
@bert-e approve

2019-08-27 15:45 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-2274/exit-process` into
`development/7.4`
* [w/7.5/bugfix/S3C-2274/exit-process](https://github.com/scality/cloudserver/compare/development/7.5...w/7.5/bugfix/S3C-2274/exit-process) will be merged into `development/7.5` (pull request #2097)
* [w/8.1/bugfix/S3C-2274/exit-process](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/S3C-2274/exit-process) will be merged into `development/8.1` (pull request #2098)



The following branches will **NOT** be impacted:

* `development/6.4`
* `stabilization/7.5.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.







*The following options are set:* **approve**

2019-08-27 16:02 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/2243e94f7c24919ad4f75ff917e99da0a9eed221) did not succeed in branch w/7.5/bugfix/S3C-2274/exit-process.




*The following options are set:* **approve**

2019-08-27 16:09 UTC, nicolas2bert commented
@bert-e reset

2019-08-27 16:09 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2019-08-27 16:09 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-2274/exit-process` into
`development/7.4`
* [w/7.5/bugfix/S3C-2274/exit-process](https://github.com/scality/cloudserver/compare/development/7.5...w/7.5/bugfix/S3C-2274/exit-process) will be merged into `development/7.5` (pull request #2099)
* [w/8.1/bugfix/S3C-2274/exit-process](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/S3C-2274/exit-process) will be merged into `development/8.1` (pull request #2100)



The following branches will **NOT** be impacted:

* `development/6.4`
* `stabilization/7.5.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.







*The following options are set:* **approve**

2019-08-27 16:21 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/7f36eff8c37d1e6dd27f4cefc860ad1e34232185) did not succeed in branch w/8.1/bugfix/S3C-2274/exit-process.




*The following options are set:* **approve**

2019-08-27 16:26 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/0c6181bb382f148bb989b33b7c6f559bbe5f9622) did not succeed in branch w/7.5/bugfix/S3C-2274/exit-process.




*The following options are set:* **approve**

2019-08-27 16:59 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/7.4`

* :heavy_check_mark: `development/7.5`

* :heavy_check_mark: `development/8.1`



The following branches will **NOT** be impacted:

* `development/6.4`
* `stabilization/7.5.0`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2019-08-27 16:59 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/7.4`

* :heavy_check_mark: `development/7.5`

* :heavy_check_mark: `development/8.1`



The following branches have **NOT** changed:

* `development/6.4`
* `stabilization/7.5.0`



Please check the status of the associated issue S3C-2274.

Goodbye nicolas2bert.

2019-08-27 16:59 UTC, merged