Bugfix/s3 c 2544 diff acct metrics
scality/cloudserver pull request #2344
Opened 2020-02-12 01:15 UTC by dora-korpar

Fix for incorrect metric handling. Previously, metrics were collected solely based on the requester. With this fix, if an account makes a stat-changing request (i.e. puts or deletes an object) in a different account's bucket, the bucket owner's metrics will be updated instead of the requester's.

2020-02-12 01:15 UTC, bert-e commented
# Hello dora-korpar,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/cloudserver/bert-e/doc/user).





*Status report is not available.*

2020-02-12 01:15 UTC, bert-e commented
# History mismatch



Merge commit #9e2252d26a42b94b85c88e44491f72b7517ef47d on the integration branch
`w/7.6/bugfix/S3C-2544-diff-acct-metrics` is merging a branch which is neither the current
branch `bugfix/S3C-2544-diff-acct-metrics` nor the development branch
`development/7.6`.

It is likely due to a rebase of the branch `bugfix/S3C-2544-diff-acct-metrics` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-02-12 23:08 UTC, dora-korpar commented
@bert-e reset

2020-02-12 23:08 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2020-02-12 23:08 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-2544-diff-acct-metrics` into
`development/7.4`
* [w/7.6/bugfix/S3C-2544-diff-acct-metrics](https://github.com/scality/cloudserver/compare/development/7.6...w/7.6/bugfix/S3C-2544-diff-acct-metrics) will be merged into `development/7.6` (pull request #2345)
* [w/7.7/bugfix/S3C-2544-diff-acct-metrics](https://github.com/scality/cloudserver/compare/development/7.7...w/7.7/bugfix/S3C-2544-diff-acct-metrics) will be merged into `development/7.7` (pull request #2346)
* [w/8.1/bugfix/S3C-2544-diff-acct-metrics](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/S3C-2544-diff-acct-metrics) will be merged into `development/8.1` (pull request #2347)
* [w/8.2/bugfix/S3C-2544-diff-acct-metrics](https://github.com/scality/cloudserver/compare/development/8.2...w/8.2/bugfix/S3C-2544-diff-acct-metrics) will be merged into `development/8.2` (pull request #2348)



The following branches will **NOT** be impacted:

* `development/6.4`
* `stabilization/7.4.5`
* `stabilization/7.6.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2020-02-12 23:08 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rachedbenmustapha

* @dora-korpar

* @rahulreddy

2020-02-14 00:28 UTC, rahulreddy requested changes
Removing `authInfo` altogether means you are no longer sending userId i.e not capturing user level metrics anymore. If you keep it instead of removing it, you can make this change in pushMetric. Let me add a commit to your change.

2020-02-14 00:29 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rachedbenmustapha

* @dora-korpar

* @rahulreddy





The following reviewers are expecting changes from the author, or must review again:

* @rahulreddy

2020-02-14 06:02 UTC, bert-e commented
# History mismatch



Merge commit #5b38b51ede3a160ab02af48f8c017d8444f1d4c2 on the integration branch
`w/7.6/bugfix/S3C-2544-diff-acct-metrics` is merging a branch which is neither the current
branch `bugfix/S3C-2544-diff-acct-metrics` nor the development branch
`development/7.6`.

It is likely due to a rebase of the branch `bugfix/S3C-2544-diff-acct-metrics` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-02-14 06:22 UTC, dora-korpar commented
@bert-e reset

2020-02-14 06:23 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2020-02-14 06:23 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-2544-diff-acct-metrics` into
`development/7.4`
* [w/7.6/bugfix/S3C-2544-diff-acct-metrics](https://github.com/scality/cloudserver/compare/development/7.6...w/7.6/bugfix/S3C-2544-diff-acct-metrics) will be merged into `development/7.6` (pull request #2349)
* [w/7.7/bugfix/S3C-2544-diff-acct-metrics](https://github.com/scality/cloudserver/compare/development/7.7...w/7.7/bugfix/S3C-2544-diff-acct-metrics) will be merged into `development/7.7` (pull request #2350)
* [w/8.1/bugfix/S3C-2544-diff-acct-metrics](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/S3C-2544-diff-acct-metrics) will be merged into `development/8.1` (pull request #2351)
* [w/8.2/bugfix/S3C-2544-diff-acct-metrics](https://github.com/scality/cloudserver/compare/development/8.2...w/8.2/bugfix/S3C-2544-diff-acct-metrics) will be merged into `development/8.2` (pull request #2352)



The following branches will **NOT** be impacted:

* `development/6.4`
* `stabilization/7.4.5`
* `stabilization/7.6.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2020-02-14 06:23 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rachedbenmustapha

* @dora-korpar

* @rahulreddy





The following reviewers are expecting changes from the author, or must review again:

* @rahulreddy

2020-02-14 06:32 UTC, naren-rajendran approved these changes

2020-02-18 21:47 UTC, rahulreddy approved these changes

2020-02-18 21:47 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rachedbenmustapha

* @dora-korpar

* @rahulreddy

2020-02-18 23:45 UTC, dora-korpar commented
@bert-e approve

2020-02-18 23:45 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/e2b8666ec6ec6738795580dabdc922c9d3b2a165) did not succeed in branch w/7.6/bugfix/S3C-2544-diff-acct-metrics.




*The following options are set:* **approve**

2020-02-19 00:04 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/27ed0058a6ced3930c0d4288923d6f7277d6b259) did not succeed in branch w/8.1/bugfix/S3C-2544-diff-acct-metrics.




*The following options are set:* **approve**

2020-02-19 18:16 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/7.4`

* :heavy_check_mark: `development/7.6`

* :heavy_check_mark: `development/7.7`

* :heavy_check_mark: `development/8.1`

* :heavy_check_mark: `development/8.2`



The following branches will **NOT** be impacted:

* `development/6.4`
* `stabilization/7.4.5`
* `stabilization/7.6.0`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2020-02-19 18:16 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/7.4`

* :heavy_check_mark: `development/7.6`

* :heavy_check_mark: `development/7.7`

* :heavy_check_mark: `development/8.1`

* :heavy_check_mark: `development/8.2`



The following branches have **NOT** changed:

* `development/6.4`
* `stabilization/7.4.5`
* `stabilization/7.6.0`



Please check the status of the associated issue S3C-2544.

Goodbye dora-korpar.

2020-02-19 18:17 UTC, merged