Update arsenal for downstream fix
scality/cloudserver pull request #2449
Opened 2020-04-15 23:20 UTC by miniscruff

# Pull request template

## Description
Downstream fix for utf8 characters in tags from Arsenal

bugfix: S3C-2668

2020-04-15 23:20 UTC, bert-e commented
# Hello miniscruff,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/cloudserver/bert-e/doc/user).





*Status report is not available.*

2020-04-15 23:20 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` with contents from `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix`
and `development/7.6`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix origin/development/7.6
 $ git merge origin/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
```

2020-04-15 23:33 UTC, miniscruff commented
@bert-e reset

2020-04-15 23:33 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2020-04-15 23:33 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` with contents from `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix`
and `development/7.6`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix origin/development/7.6
 $ git merge origin/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
```

2020-04-15 23:35 UTC, miniscruff commented
@bert-e help

2020-04-15 23:35 UTC, bert-e commented
# Help page



The following options and commands are available at this time.

## Options ##


name   | description  | privileged   | authored
------ | ------------ | ------------ |----------
:arrow_right: **bypass_build_status** | Bypass the build and test status |  :star:  | 
:arrow_right: **bypass_jira_check** | Bypass the Jira issue check |  :star:  | 
:arrow_right: **approve** | Instruct Bert-E that the author has approved the pull request. |  |  :writing_hand: 
:arrow_right: **unanimity** | Change review acceptance criteria from `one reviewer at least` to `all reviewers` |  | 
:arrow_right: **bypass_author_approval** | Bypass the pull request author's approval |  :star:  | 
:arrow_right: **bypass_peer_approval** | Bypass the pull request peers' approval |  :star:  | 
:arrow_right: **bypass_commit_size** | Bypass the check on the size of the changeset ```TBA``` |  :star:  | 
:arrow_right: **no_octopus** | Prevent Wall-E from doing any octopus merge and use multiple consecutive merge instead |  | 
:arrow_right: **bypass_incompatible_branch** | Bypass the check on the source branch prefix |  :star:  | 
:arrow_right: **after_pull_request** | Wait for the given pull request id to be merged before continuing with the current one. |  | 
:arrow_right: **bypass_leader_approval** | Bypass the pull request leaders' approval |  :star:  | 
:arrow_right: **create_pull_requests** | Allow the creation of integration pull requests. |  | 
:arrow_right: **wait** | Instruct Bert-E not to run until further notice. |  | 



## Commands ##


name   | description  | privileged
------ | ------------ | ------------
:arrow_right: **retry** | Re-start a fresh build ```TBA``` | 
:arrow_right: **reset** | Try to remove integration branches unless there are commits on them which do not appear on the source branch. | 
:arrow_right: **force_reset** | Delete integration branches & pull requests, and restart merge process from the beginning. | 
:arrow_right: **help** | Print Bert-E's manual in the pull request. | 
:arrow_right: **build** | Re-start a fresh build ```TBA``` | 
:arrow_right: **clear** | Remove all comments from Bert-E from the history ```TBA``` | 
:arrow_right: **status** | Print Bert-E's current status in the pull request ```TBA``` |

2020-04-15 23:35 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` with contents from `w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix`
and `development/7.7`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix origin/development/7.7
 $ git merge origin/w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
```

2020-04-15 23:36 UTC, miniscruff commented
@bert-e help

2020-04-15 23:36 UTC, bert-e commented
# Help page



The following options and commands are available at this time.

## Options ##


name   | description  | privileged   | authored
------ | ------------ | ------------ |----------
:arrow_right: **bypass_build_status** | Bypass the build and test status |  :star:  | 
:arrow_right: **bypass_jira_check** | Bypass the Jira issue check |  :star:  | 
:arrow_right: **approve** | Instruct Bert-E that the author has approved the pull request. |  |  :writing_hand: 
:arrow_right: **unanimity** | Change review acceptance criteria from `one reviewer at least` to `all reviewers` |  | 
:arrow_right: **bypass_author_approval** | Bypass the pull request author's approval |  :star:  | 
:arrow_right: **bypass_peer_approval** | Bypass the pull request peers' approval |  :star:  | 
:arrow_right: **bypass_commit_size** | Bypass the check on the size of the changeset ```TBA``` |  :star:  | 
:arrow_right: **no_octopus** | Prevent Wall-E from doing any octopus merge and use multiple consecutive merge instead |  | 
:arrow_right: **bypass_incompatible_branch** | Bypass the check on the source branch prefix |  :star:  | 
:arrow_right: **after_pull_request** | Wait for the given pull request id to be merged before continuing with the current one. |  | 
:arrow_right: **bypass_leader_approval** | Bypass the pull request leaders' approval |  :star:  | 
:arrow_right: **create_pull_requests** | Allow the creation of integration pull requests. |  | 
:arrow_right: **wait** | Instruct Bert-E not to run until further notice. |  | 



## Commands ##


name   | description  | privileged
------ | ------------ | ------------
:arrow_right: **retry** | Re-start a fresh build ```TBA``` | 
:arrow_right: **reset** | Try to remove integration branches unless there are commits on them which do not appear on the source branch. | 
:arrow_right: **force_reset** | Delete integration branches & pull requests, and restart merge process from the beginning. | 
:arrow_right: **help** | Print Bert-E's manual in the pull request. | 
:arrow_right: **build** | Re-start a fresh build ```TBA``` | 
:arrow_right: **clear** | Remove all comments from Bert-E from the history ```TBA``` | 
:arrow_right: **status** | Print Bert-E's current status in the pull request ```TBA``` |

2020-04-15 23:36 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` with contents from `w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix`
and `development/7.7`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix origin/development/7.7
 $ git merge origin/w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
```

2020-04-15 23:41 UTC, miniscruff commented
@bert-e help

2020-04-15 23:41 UTC, bert-e commented
# Help page



The following options and commands are available at this time.

## Options ##


name   | description  | privileged   | authored
------ | ------------ | ------------ |----------
:arrow_right: **bypass_build_status** | Bypass the build and test status |  :star:  | 
:arrow_right: **bypass_jira_check** | Bypass the Jira issue check |  :star:  | 
:arrow_right: **approve** | Instruct Bert-E that the author has approved the pull request. |  |  :writing_hand: 
:arrow_right: **unanimity** | Change review acceptance criteria from `one reviewer at least` to `all reviewers` |  | 
:arrow_right: **bypass_author_approval** | Bypass the pull request author's approval |  :star:  | 
:arrow_right: **bypass_peer_approval** | Bypass the pull request peers' approval |  :star:  | 
:arrow_right: **bypass_commit_size** | Bypass the check on the size of the changeset ```TBA``` |  :star:  | 
:arrow_right: **no_octopus** | Prevent Wall-E from doing any octopus merge and use multiple consecutive merge instead |  | 
:arrow_right: **bypass_incompatible_branch** | Bypass the check on the source branch prefix |  :star:  | 
:arrow_right: **after_pull_request** | Wait for the given pull request id to be merged before continuing with the current one. |  | 
:arrow_right: **bypass_leader_approval** | Bypass the pull request leaders' approval |  :star:  | 
:arrow_right: **create_pull_requests** | Allow the creation of integration pull requests. |  | 
:arrow_right: **wait** | Instruct Bert-E not to run until further notice. |  | 



## Commands ##


name   | description  | privileged
------ | ------------ | ------------
:arrow_right: **retry** | Re-start a fresh build ```TBA``` | 
:arrow_right: **reset** | Try to remove integration branches unless there are commits on them which do not appear on the source branch. | 
:arrow_right: **force_reset** | Delete integration branches & pull requests, and restart merge process from the beginning. | 
:arrow_right: **help** | Print Bert-E's manual in the pull request. | 
:arrow_right: **build** | Re-start a fresh build ```TBA``` | 
:arrow_right: **clear** | Remove all comments from Bert-E from the history ```TBA``` | 
:arrow_right: **status** | Print Bert-E's current status in the pull request ```TBA``` |

2020-04-15 23:41 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` with contents from `w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix`
and `development/8.1`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix origin/development/8.1
 $ git merge origin/w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
```

2020-04-15 23:46 UTC, miniscruff commented
@bert-e clear

2020-04-15 23:46 UTC, bert-e commented
# Not implemented



This command will be implemented soon.

2020-04-15 23:46 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` into
`development/7.4`
* [w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix](https://github.com/scality/cloudserver/compare/development/7.6...w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix) will be merged into `development/7.6` (pull request #2450)
* [w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix](https://github.com/scality/cloudserver/compare/development/7.7...w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix) will be merged into `development/7.7` (pull request #2451)
* [w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix) will be merged into `development/8.1` (pull request #2452)
* [w/8.2/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix](https://github.com/scality/cloudserver/compare/development/8.2...w/8.2/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix) will be merged into `development/8.2` (pull request #2453)



The following branches will **NOT** be impacted:

* `development/6.4`
* `stabilization/7.4.5`
* `stabilization/7.6.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2020-04-15 23:46 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rachedbenmustapha

* @dora-korpar

* @rahulreddy

2020-04-16 22:38 UTC, ilkescality commented on tests/unit/api/objectPut.js
> +        { tagging: `${'w'.repeat(129)}=value1`, error: invalidTag },
good catch

2020-04-16 22:38 UTC, ilkescality approved these changes

2020-04-16 22:43 UTC, tmacro approved these changes

2020-04-16 22:45 UTC, alexanderchan-scality approved these changes

2020-04-16 23:15 UTC, jonathan-gramain requested changes
I did a similar comment in one of @ilkescality 's PR: you will need to update the dependency hash on the integration PRs by doing the following on each:

When it's time to resolve conflicts on `w/x.y/...`, update `package.json` with the latest commit hash of the matching dependency branch, eg. the latest `development/8.1` of arsenal when working on `w/8.1/...`, that contains your fix

Then:

```
git reset yarn.lock
git checkout yarn.lock
rm -rf node_modules
yarn install
git add yarn.lock package.json
git commit
```

2020-04-16 23:15 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rachedbenmustapha

* @dora-korpar

* @rahulreddy





The following reviewers are expecting changes from the author, or must review again:

* @jonathan-gramain

2020-04-16 23:34 UTC, miniscruff commented
> I did a similar comment in one of @ilkescality 's PR: you will need to update the dependency hash on the integration PRs by doing the following on each:
> 
> When it's time to resolve conflicts on `w/x.y/...`, update `package.json` with the latest commit hash of the matching dependency branch, eg. the latest `development/8.1` of arsenal when working on `w/8.1/...`, that contains your fix
> 
> Then:
> 
> ```
> git reset yarn.lock
> git checkout yarn.lock
> rm -rf node_modules
> yarn install
> git add yarn.lock package.json
> git commit
> ```

I went through each of the integration branches and did:
```
git checkout ...
git merge ...
# this failed with a conflict
# resolve conflict to use new hash
yarn install
git add, commit, push
```

This was required because each one had a conflict and failed from 7.6 onwards. I can go through them again but I think this should be done already.

2020-04-16 23:55 UTC, jonathan-gramain commented
> > I did a similar comment in one of @ilkescality 's PR: you will need to update the dependency hash on the integration PRs by doing the following on each:
> > When it's time to resolve conflicts on `w/x.y/...`, update `package.json` with the latest commit hash of the matching dependency branch, eg. the latest `development/8.1` of arsenal when working on `w/8.1/...`, that contains your fix
> > Then:
> > ```
> > git reset yarn.lock
> > git checkout yarn.lock
> > rm -rf node_modules
> > yarn install
> > git add yarn.lock package.json
> > git commit
> > ```
> 
> I went through each of the integration branches and did:
> 
> ```
> git checkout ...
> git merge ...
> # this failed with a conflict
> # resolve conflict to use new hash
> yarn install
> git add, commit, push
> ```
> 
> This was required because each one had a conflict and failed from 7.6 onwards. I can go through them again but I think this should be done already.

In `package.json`, the commit hash is the same for this PR and all integration PRs opened by bert-e. They should reflect their respective arsenal branch after the conflict resolution, which is a different hash at least between 7.4 and 8.1 (I think arsenal has less branches than cloudserver, e.g. no development/8.2, in which case bert-e should be able to merge automatically in `w/8.2` from `w/8.1` without manual conflict resolution).

2020-04-17 00:00 UTC, miniscruff commented
> > > I did a similar comment in one of @ilkescality 's PR: you will need to update the dependency hash on the integration PRs by doing the following on each:
> > > When it's time to resolve conflicts on `w/x.y/...`, update `package.json` with the latest commit hash of the matching dependency branch, eg. the latest `development/8.1` of arsenal when working on `w/8.1/...`, that contains your fix
> > > Then:
> > > ```
> > > git reset yarn.lock
> > > git checkout yarn.lock
> > > rm -rf node_modules
> > > yarn install
> > > git add yarn.lock package.json
> > > git commit
> > > ```
> > 
> > 
> > I went through each of the integration branches and did:
> > ```
> > git checkout ...
> > git merge ...
> > # this failed with a conflict
> > # resolve conflict to use new hash
> > yarn install
> > git add, commit, push
> > ```
> > 
> > 
> > This was required because each one had a conflict and failed from 7.6 onwards. I can go through them again but I think this should be done already.
> 
> In `package.json`, the commit hash is the same for this PR and all integration PRs opened by bert-e. They should reflect their respective arsenal branch after the conflict resolution, which is a different hash at least between 7.4 and 8.1 (I think arsenal has less branches than cloudserver, e.g. no development/8.2, in which case bert-e should be able to merge automatically in `w/8.2` from `w/8.1` without manual conflict resolution).

oh so use the commit hash from arsenal that matches each development/x version and not the 7.4 version I used each time... got it.

2020-04-17 02:23 UTC, jonathan-gramain approved these changes
Approving in advance since I will be off tomorrow

2020-04-17 02:24 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rachedbenmustapha

* @dora-korpar

* @rahulreddy

2020-04-17 05:42 UTC, bert-e commented
# Conflict




A conflict has been raised during the update of
integration branch `w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` with contents from `w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix`
and `development/7.7`.

Please resolve the conflict on **the integration branch** (`w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix`).


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
 $ git pull  # or "git reset --hard origin/w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix"
 $ git merge origin/development/7.7
 $ # <intense conflict resolution>
 $ git commit
 $ git merge origin/w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
```

2020-04-17 05:51 UTC, bert-e commented
# Conflict




A conflict has been raised during the update of
integration branch `w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` with contents from `w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix`
and `development/8.1`.

Please resolve the conflict on **the integration branch** (`w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix`).


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
 $ git pull  # or "git reset --hard origin/w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix"
 $ git merge origin/development/8.1
 $ # <intense conflict resolution>
 $ git commit
 $ git merge origin/w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
```

2020-04-17 06:02 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rachedbenmustapha

* @dora-korpar

* @rahulreddy

2020-04-17 06:03 UTC, miniscruff commented
Ok for anyone joining late, I went through each of the integration PRs to update the arsenal git hash to the one from the arsenal integration PRs for each version... I think everything is ready now but would not be surprised if I missed something.

2020-04-17 06:20 UTC, bert-e commented
# History mismatch



Merge commit #95762123abb5175be85adf4f58845525bc23f0c1 on the integration branch
`w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` is merging a branch which is neither the current
branch `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` nor the development branch
`development/7.7`.

It is likely due to a rebase of the branch `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-04-17 06:22 UTC, miniscruff commented
@bert-e reset

2020-04-17 06:22 UTC, bert-e commented
# Lossy reset warning



There seems to be *manual* commits on integration branches (e.g. conflict
resolutions) that will be lost if you chose to *reset*.

**You can use the `force_reset` command if you still want me
to delete those branches.**

2020-04-17 06:22 UTC, bert-e commented
# History mismatch



Merge commit #95762123abb5175be85adf4f58845525bc23f0c1 on the integration branch
`w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` is merging a branch which is neither the current
branch `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` nor the development branch
`development/7.7`.

It is likely due to a rebase of the branch `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-04-17 06:22 UTC, miniscruff commented
@bert-e force_reset

2020-04-17 06:22 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2020-04-17 06:23 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` with contents from `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix`
and `development/7.6`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix origin/development/7.6
 $ git merge origin/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
```

2020-04-17 06:29 UTC, miniscruff commented
@bert-e status

2020-04-17 06:29 UTC, bert-e commented
# Status





*Status report is not available.*

2020-04-17 06:29 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` with contents from `w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix`
and `development/7.7`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix origin/development/7.7
 $ git merge origin/w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
```

2020-04-17 06:35 UTC, miniscruff commented
@bert-e status

2020-04-17 06:35 UTC, bert-e commented
# Status





*Status report is not available.*

2020-04-17 06:35 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` with contents from `w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix`
and `development/8.1`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix origin/development/8.1
 $ git merge origin/w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
```

2020-04-17 06:39 UTC, miniscruff commented
@bert-e status

2020-04-17 06:39 UTC, bert-e commented
# Status





*Status report is not available.*

2020-04-17 06:39 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` into
`development/7.4`
* [w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix](https://github.com/scality/cloudserver/compare/development/7.6...w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix) will be merged into `development/7.6` (pull request #2459)
* [w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix](https://github.com/scality/cloudserver/compare/development/7.7...w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix) will be merged into `development/7.7` (pull request #2460)
* [w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix) will be merged into `development/8.1` (pull request #2461)
* [w/8.2/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix](https://github.com/scality/cloudserver/compare/development/8.2...w/8.2/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix) will be merged into `development/8.2` (pull request #2462)



The following branches will **NOT** be impacted:

* `development/6.4`
* `stabilization/7.4.5`
* `stabilization/7.6.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2020-04-17 06:39 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rachedbenmustapha

* @dora-korpar

* @rahulreddy

2020-04-17 06:40 UTC, miniscruff commented
ok third try or something... all the integration branches should properly be using the version from arsenal...

2020-04-17 19:06 UTC, rahulreddy approved these changes

2020-04-18 02:16 UTC, miniscruff commented
@bert-e status

2020-04-18 02:16 UTC, bert-e commented
# Status





*Status report is not available.*

2020-04-18 02:16 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include at least 1 approval from the following list:

* @rachedbenmustapha

* @dora-korpar

* @rahulreddy

2020-04-18 02:16 UTC, miniscruff commented
@bert-e approve

2020-04-18 02:16 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/7012511ad7c7bbb3d229a7c47ea3ce282f05bcb5) did not succeed in branch w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix.




*The following options are set:* **approve**

2020-04-20 17:21 UTC, miniscruff commented
@bert-e status

2020-04-20 17:21 UTC, bert-e commented
# Status





*Status report is not available.*






*The following options are set:* **approve**

2020-04-20 17:21 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/7012511ad7c7bbb3d229a7c47ea3ce282f05bcb5) did not succeed in branch w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix.




*The following options are set:* **approve**

2020-04-20 17:21 UTC, miniscruff commented
@bert-e help

2020-04-20 17:21 UTC, bert-e commented
# Help page



The following options and commands are available at this time.

## Options ##


name   | description  | privileged   | authored
------ | ------------ | ------------ |----------
:arrow_right: **bypass_build_status** | Bypass the build and test status |  :star:  | 
:arrow_right: **bypass_jira_check** | Bypass the Jira issue check |  :star:  | 
:arrow_right: **approve** | Instruct Bert-E that the author has approved the pull request. |  |  :writing_hand: 
:arrow_right: **unanimity** | Change review acceptance criteria from `one reviewer at least` to `all reviewers` |  | 
:arrow_right: **bypass_author_approval** | Bypass the pull request author's approval |  :star:  | 
:arrow_right: **bypass_peer_approval** | Bypass the pull request peers' approval |  :star:  | 
:arrow_right: **bypass_commit_size** | Bypass the check on the size of the changeset ```TBA``` |  :star:  | 
:arrow_right: **no_octopus** | Prevent Wall-E from doing any octopus merge and use multiple consecutive merge instead |  | 
:arrow_right: **bypass_incompatible_branch** | Bypass the check on the source branch prefix |  :star:  | 
:arrow_right: **after_pull_request** | Wait for the given pull request id to be merged before continuing with the current one. |  | 
:arrow_right: **bypass_leader_approval** | Bypass the pull request leaders' approval |  :star:  | 
:arrow_right: **create_pull_requests** | Allow the creation of integration pull requests. |  | 
:arrow_right: **wait** | Instruct Bert-E not to run until further notice. |  | 



## Commands ##


name   | description  | privileged
------ | ------------ | ------------
:arrow_right: **retry** | Re-start a fresh build ```TBA``` | 
:arrow_right: **reset** | Try to remove integration branches unless there are commits on them which do not appear on the source branch. | 
:arrow_right: **force_reset** | Delete integration branches & pull requests, and restart merge process from the beginning. | 
:arrow_right: **help** | Print Bert-E's manual in the pull request. | 
:arrow_right: **build** | Re-start a fresh build ```TBA``` | 
:arrow_right: **clear** | Remove all comments from Bert-E from the history ```TBA``` | 
:arrow_right: **status** | Print Bert-E's current status in the pull request ```TBA``` | 






*The following options are set:* **approve**

2020-04-20 17:21 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/7012511ad7c7bbb3d229a7c47ea3ce282f05bcb5) did not succeed in branch w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix.




*The following options are set:* **approve**

2020-04-20 20:29 UTC, rahulreddy commented on tests/functional/aws-node-sdk/lib/utility/tagging.js
> +    { tag: { key: 'w'.repeat(129), value: 'foo' },
This is a good rewrite 💯

2020-04-21 18:49 UTC, rahulreddy commented
/reset

2020-04-21 18:49 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **approve**

2020-04-21 18:50 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` with contents from `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix`
and `development/7.6`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix origin/development/7.6
 $ git merge origin/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
```





*The following options are set:* **approve**

2020-04-21 19:05 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` with contents from `w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix`
and `development/7.7`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix origin/development/7.7
 $ git merge origin/w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
```





*The following options are set:* **approve**

2020-04-21 19:24 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` with contents from `w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix`
and `development/8.1`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix origin/development/8.1
 $ git merge origin/w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix
```





*The following options are set:* **approve**

2020-04-21 20:03 UTC, bert-e commented
# History mismatch



Merge commit #30db183db0813adcc1672cdf274ae6b68635e37e on the integration branch
`w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` is merging a branch which is neither the current
branch `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` nor the development branch
`development/8.1`.

It is likely due to a rebase of the branch `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2020-04-21 20:15 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` into
`development/7.4`
* [w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix](https://github.com/scality/cloudserver/compare/development/7.6...w/7.6/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix) will be merged into `development/7.6` (pull request #2485)
* [w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix](https://github.com/scality/cloudserver/compare/development/7.7...w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix) will be merged into `development/7.7` (pull request #2486)
* [w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix) will be merged into `development/8.1` (pull request #2487)
* [w/8.2/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix](https://github.com/scality/cloudserver/compare/development/8.2...w/8.2/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix) will be merged into `development/8.2` (pull request #2488)



The following branches will **NOT** be impacted:

* `development/6.4`
* `stabilization/7.4.5`
* `stabilization/7.6.0`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.







*The following options are set:* **approve**

2020-04-21 20:15 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/915b996f9c97de887e8edbc5309b8e9fab62388a) did not succeed in branch w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix.




*The following options are set:* **approve**

2020-04-21 20:27 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/0594f9f76cf003f2505fc213abf0c96bd52b6e4d) did not succeed in branch w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix.




*The following options are set:* **approve**

2020-04-21 20:27 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/915b996f9c97de887e8edbc5309b8e9fab62388a) did not succeed in branch w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix.




*The following options are set:* **approve**

2020-04-21 20:40 UTC, bert-e commented
# History mismatch



Merge commit #915b996f9c97de887e8edbc5309b8e9fab62388a on the integration branch
`w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` is merging a branch which is neither the current
branch `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` nor the development branch
`development/8.1`.

It is likely due to a rebase of the branch `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2020-04-21 20:46 UTC, bert-e commented
# History mismatch



Merge commit #0594f9f76cf003f2505fc213abf0c96bd52b6e4d on the integration branch
`w/8.2/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` is merging a branch which is neither the current
branch `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` nor the development branch
`development/8.2`.

It is likely due to a rebase of the branch `bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**





*The following options are set:* **approve**

2020-04-21 20:55 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/54daba70e139d42a3ed23f2f23e1a0c7cb6c4e95) did not succeed in branch w/8.1/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix.




*The following options are set:* **approve**

2020-04-21 20:55 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/ba6533ff5f1b69caa06e51d74d25d3921cc1a602) did not succeed in branch w/7.7/bugfix/S3C-2668_update_arsenal_for_tagging_utf8_fix.




*The following options are set:* **approve**

2020-04-21 21:38 UTC, rahulreddy commented
/bypass_build_status

2020-04-21 21:38 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/7.4`

* :heavy_check_mark: `development/7.6`

* :heavy_check_mark: `development/7.7`

* :heavy_check_mark: `development/8.1`

* :heavy_check_mark: `development/8.2`



The following branches will **NOT** be impacted:

* `development/6.4`
* `stabilization/7.4.5`
* `stabilization/7.6.0`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **bypass_build_status, approve**

2020-04-21 22:57 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/7.4`

* :heavy_check_mark: `development/7.6`

* :heavy_check_mark: `development/7.7`

* :heavy_check_mark: `development/8.1`

* :heavy_check_mark: `development/8.2`



The following branches have **NOT** changed:

* `development/6.4`
* `stabilization/7.4.5`
* `stabilization/7.6.0`



Please check the status of the associated issue S3C-2668.

Goodbye miniscruff.

2020-04-21 22:58 UTC, merged