bf: S3C-3018 multiobject delete error
scality/cloudserver pull request #2578
Opened 2020-06-02 01:29 UTC by dora-korpar

Resolves error thrown if `multiObject Delete` fulfills this condition: https://github.com/scality/cloudserver/blob/stabilization/7.4.6/lib/api/multiObjectDelete.js#L432
Test for the fix is: https://github.com/scality/Integration/blob/stabilization/7.4.6/genericStaas/policies/tests/multiObjectDelete-versioning.js#L102

2020-06-02 01:29 UTC, bert-e commented
# Hello dora-korpar,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/cloudserver/bert-e/doc/user).





*Status report is not available.*

2020-06-02 01:29 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-3018-multiobj-delete-error` into
`stabilization/7.4.6`
* [w/7.4/bugfix/S3C-3018-multiobj-delete-error](https://github.com/scality/cloudserver/compare/development/7.4...w/7.4/bugfix/S3C-3018-multiobj-delete-error) will be merged into `development/7.4` (pull request #2579)
* [w/7.7/bugfix/S3C-3018-multiobj-delete-error](https://github.com/scality/cloudserver/compare/development/7.7...w/7.7/bugfix/S3C-3018-multiobj-delete-error) will be merged into `development/7.7` (pull request #2580)
* [w/7.8/bugfix/S3C-3018-multiobj-delete-error](https://github.com/scality/cloudserver/compare/development/7.8...w/7.8/bugfix/S3C-3018-multiobj-delete-error) will be merged into `development/7.8` (pull request #2581)
* [w/8.1/bugfix/S3C-3018-multiobj-delete-error](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/S3C-3018-multiobj-delete-error) will be merged into `development/8.1` (pull request #2582)
* [w/8.2/bugfix/S3C-3018-multiobj-delete-error](https://github.com/scality/cloudserver/compare/development/8.2...w/8.2/bugfix/S3C-3018-multiobj-delete-error) will be merged into `development/8.2` (pull request #2583)



The following branches will **NOT** be impacted:

* `development/6.4`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2020-06-02 01:29 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include a mandatory approval from @dora-korpar.

2020-06-02 05:54 UTC, miniscruff approved these changes

2020-06-03 18:27 UTC, rahulreddy requested changes
Hey @dora-korpar . Please add two commits for any bugfix PRs
- first commit should be a test identifying the bug
- second commit should be the fix showing that it makes the test pass in the first commit

2020-06-03 18:28 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include a mandatory approval from @dora-korpar.




The following reviewers are expecting changes from the author, or must review again:

* @rahulreddy

2020-06-05 03:24 UTC, bert-e commented
# History mismatch



Merge commit #7070b8882e48bc0f824643e1ae3ae0183930934c on the integration branch
`w/7.4/bugfix/S3C-3018-multiobj-delete-error` is merging a branch which is neither the current
branch `bugfix/S3C-3018-multiobj-delete-error` nor the development branch
`development/7.4`.

It is likely due to a rebase of the branch `bugfix/S3C-3018-multiobj-delete-error` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-06-10 01:02 UTC, dora-korpar commented
@bert-e reset

2020-06-10 01:02 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2020-06-10 01:03 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-3018-multiobj-delete-error` into
`stabilization/7.4.6`
* [w/7.4/bugfix/S3C-3018-multiobj-delete-error](https://github.com/scality/cloudserver/compare/development/7.4...w/7.4/bugfix/S3C-3018-multiobj-delete-error) will be merged into `development/7.4` (pull request #2618)
* [w/7.7/bugfix/S3C-3018-multiobj-delete-error](https://github.com/scality/cloudserver/compare/development/7.7...w/7.7/bugfix/S3C-3018-multiobj-delete-error) will be merged into `development/7.7` (pull request #2619)
* [w/7.8/bugfix/S3C-3018-multiobj-delete-error](https://github.com/scality/cloudserver/compare/development/7.8...w/7.8/bugfix/S3C-3018-multiobj-delete-error) will be merged into `development/7.8` (pull request #2620)
* [w/8.1/bugfix/S3C-3018-multiobj-delete-error](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/S3C-3018-multiobj-delete-error) will be merged into `development/8.1` (pull request #2621)
* [w/8.2/bugfix/S3C-3018-multiobj-delete-error](https://github.com/scality/cloudserver/compare/development/8.2...w/8.2/bugfix/S3C-3018-multiobj-delete-error) will be merged into `development/8.2` (pull request #2622)



The following branches will **NOT** be impacted:

* `development/6.4`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2020-06-10 01:03 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include a mandatory approval from @dora-korpar.




The following reviewers are expecting changes from the author, or must review again:

* @rahulreddy

2020-06-10 01:11 UTC, rahulreddy approved these changes

2020-06-10 01:11 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include a mandatory approval from @dora-korpar.

2020-06-10 01:12 UTC, dora-korpar commented
@bert-e approve

2020-06-10 01:12 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/605f1d3048737ae66f2d17c14530ccb20804e19e) did not succeed in branch w/7.4/bugfix/S3C-3018-multiobj-delete-error.




*The following options are set:* **approve**

2020-06-10 02:41 UTC, ilkescality approved these changes

2020-06-10 04:31 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/6db9164b1a7ea2a36dcec259dd57e55c6f5dfe5b) did not succeed in branch w/8.1/bugfix/S3C-3018-multiobj-delete-error.




*The following options are set:* **approve**

2020-06-10 05:04 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `stabilization/7.4.6`

* :heavy_check_mark: `development/7.4`

* :heavy_check_mark: `development/7.7`

* :heavy_check_mark: `development/7.8`

* :heavy_check_mark: `development/8.1`

* :heavy_check_mark: `development/8.2`



The following branches will **NOT** be impacted:

* `development/6.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2020-06-10 05:04 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `stabilization/7.4.6`

* :heavy_check_mark: `development/7.4`

* :heavy_check_mark: `development/7.7`

* :heavy_check_mark: `development/7.8`

* :heavy_check_mark: `development/8.1`

* :heavy_check_mark: `development/8.2`



The following branches have **NOT** changed:

* `development/6.4`



Please check the status of the associated issue S3C-3018.

Goodbye dora-korpar.

2020-06-10 05:04 UTC, merged