bf(S3C-3263): Fix objectDelta field values
scality/cloudserver pull request #2951
Opened 2020-08-14 19:35 UTC by tmacro

# Pull request template

## Description

### Motivation and context

Why is this change required? What problem does it solve?

### Related issues

Please use the following link syntaxes #600 to reference issues in the
current repository

## Checklist

### Add tests to cover the changes

New tests added or existing tests modified to cover all changes

### Code conforms with the [style guide](https://github.com/scality/Guidelines/blob/master/CONTRIBUTING.md#coding-style-guidelines)

### Sign your work

In order to contribute to the project, you must sign your work
https://github.com/scality/Guidelines/blob/master/CONTRIBUTING.md#sign-your-work

Thank you again for contributing! We will try to test and integrate the change
as soon as we can.

2020-08-14 19:35 UTC, bert-e commented
# Hello tmacro,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/cloudserver/bert-e/doc/user).





*Status report is not available.*

2020-08-14 19:35 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-3263_incorrect_objectDelta` into
`development/7.8`
* [w/8.1/bugfix/S3C-3263_incorrect_objectDelta](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/S3C-3263_incorrect_objectDelta) will be merged into `development/8.1` (pull request #2952)
* [w/8.2/bugfix/S3C-3263_incorrect_objectDelta](https://github.com/scality/cloudserver/compare/development/8.2...w/8.2/bugfix/S3C-3263_incorrect_objectDelta) will be merged into `development/8.2` (pull request #2953)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `stabilization/7.4.7`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2020-08-14 19:35 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include a mandatory approval from @dora-korpar.

2020-08-14 19:41 UTC, rahulreddy requested changes

2020-08-14 19:41 UTC, rahulreddy commented on lib/api/multipartDelete.js
> +                    numberOfObjects: 1,
We don't have to set `numberOfObjects` here as it's not counted until mpu is finished

2020-08-14 19:41 UTC, rahulreddy commented on lib/api/objectPutPart.js
> +            numberOfObjects: 1,
Same here, we don't need to increment `numberOfObjects` here. It gets incremented in complete mpu api.

2020-08-14 19:41 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include a mandatory approval from @dora-korpar.




The following reviewers are expecting changes from the author, or must review again:

* @rahulreddy

2020-08-14 19:44 UTC, bert-e commented
# History mismatch



Merge commit #43153a42c5f90f2bbfc66d124342fc3e490b5c36 on the integration branch
`w/8.1/bugfix/S3C-3263_incorrect_objectDelta` is merging a branch which is neither the current
branch `bugfix/S3C-3263_incorrect_objectDelta` nor the development branch
`development/8.1`.

It is likely due to a rebase of the branch `bugfix/S3C-3263_incorrect_objectDelta` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2020-08-14 19:47 UTC, tmacro commented
/reset

2020-08-14 19:47 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2020-08-14 19:47 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `bugfix/S3C-3263_incorrect_objectDelta` into
`development/7.8`
* [w/8.1/bugfix/S3C-3263_incorrect_objectDelta](https://github.com/scality/cloudserver/compare/development/8.1...w/8.1/bugfix/S3C-3263_incorrect_objectDelta) will be merged into `development/8.1` (pull request #2954)
* [w/8.2/bugfix/S3C-3263_incorrect_objectDelta](https://github.com/scality/cloudserver/compare/development/8.2...w/8.2/bugfix/S3C-3263_incorrect_objectDelta) will be merged into `development/8.2` (pull request #2955)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `stabilization/7.4.7`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2020-08-14 19:47 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include a mandatory approval from @dora-korpar.




The following reviewers are expecting changes from the author, or must review again:

* @rahulreddy

2020-08-14 22:11 UTC, jonathan-gramain approved these changes

2020-08-15 04:14 UTC, rahulreddy approved these changes

2020-08-15 04:14 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include a mandatory approval from @dora-korpar.

2020-08-15 16:51 UTC, rahulreddy commented
/bypass_leader_approval

2020-08-15 16:52 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers





Peer approvals *must* include a mandatory approval from @dora-korpar.









*The following options are set:* **bypass_leader_approval**

2020-08-15 17:00 UTC, tmacro commented
/approve

2020-08-15 17:00 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/7.8`

* :heavy_check_mark: `development/8.1`

* :heavy_check_mark: `development/8.2`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.4`
* `stabilization/7.4.7`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **bypass_leader_approval, approve**

2020-08-15 17:01 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/7.8`

* :heavy_check_mark: `development/8.1`

* :heavy_check_mark: `development/8.2`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.4`
* `stabilization/7.4.7`



Please check the status of the associated issue S3C-3263.

Goodbye tmacro.

2020-08-15 17:01 UTC, merged