CLDSRV-34 - fix time computation for test comparison
scality/cloudserver pull request #3931
Opened 2021-10-11 16:41 UTC by lavigne958

need a new date that is 30 minutes in the past.
Computation is based on a date already 30 minutes in the future,
take that date and rewind it by 60 minutes
- 30 to go back to the original data
- 30 to go back 30 minutes in the past

# Pull request template

## Description

### Motivation and context

This change is required as it brakes a unit test

2021-10-11 16:41 UTC, bert-e commented
# Hello lavigne958,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/cloudserver/bert-e/doc/user).





*Status report is not available.*

2021-10-11 16:41 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue CLDSRV-34 contains:


* *None*



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.2.14`


Please check the `Fix Version/s` of CLDSRV-34, or the target
branch of this pull request.

2021-10-11 16:43 UTC, lavigne958 commented
Hey bert-e

2021-10-11 16:43 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-10-11 16:55 UTC, miniscruff requested changes

2021-10-11 16:55 UTC, miniscruff commented on tests/unit/api/objectHead.js
> +const earlierDate = date.setMinutes(date.getMinutes() - 60);
I think the problem here is that date is being changed with each method as setMinutes updates in place.
You probably want to do `laterDate = new Date().setMinutes(...);` and so on.

2021-10-11 16:55 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @miniscruff

2021-10-11 16:56 UTC, miniscruff commented on tests/unit/api/objectHead.js
> +const earlierDate = date.setMinutes(date.getMinutes() - 60);
Actually on second thought I think just doing two calls is better.
```js
const earlierDate = new Date();
earlierDate.setMinutes(...);
```

2021-10-12 09:24 UTC, lavigne958 commented on tests/unit/api/objectHead.js
> +const earlierDate = date.setMinutes(date.getMinutes() - 60);
Right it actually looks easier to read and understand.

2021-10-12 18:21 UTC, miniscruff approved these changes

2021-10-12 18:21 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-10-13 12:33 UTC, XinLi0207 approved these changes

2021-10-13 12:38 UTC, lavigne958 commented
squashed commits and rebased PR.

2021-10-13 12:38 UTC, lavigne958 commented
/approve

2021-10-13 13:15 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/829a22fe944418d34c4a5183e1875df900bb9c0b) did not succeed in branch bugfix/CLDSRV-34_fix_bad_date_computation.




*The following options are set:* **approve**

2021-10-13 16:27 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.2`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.10`
* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-10-13 16:27 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.2`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.10`
* `development/7.4`



Please check the status of the associated issue CLDSRV-34.

Goodbye lavigne958.

2021-10-13 16:27 UTC, merged