Allow configuring CLDSRV-41 capability
scality/cloudserver pull request #3975
Opened 2021-10-22 14:37 UTC by francoisferrand

Issue: CLDSRV-41
Issue: ARTESCA-2190

2021-10-22 14:37 UTC, bert-e commented
# Hello francoisferrand,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/cloudserver/bert-e/doc/user).





*Status report is not available.*

2021-10-22 14:37 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue CLDSRV-41 contains:


* `8.2.15`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.2.16`


Please check the `Fix Version/s` of CLDSRV-41, or the target
branch of this pull request.

2021-10-22 17:20 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-10-22 17:32 UTC, francoisferrand commented
fixed version in ticket

2021-10-25 07:23 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue CLDSRV-41 contains:


* `8.2.16`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.2.17`


Please check the `Fix Version/s` of CLDSRV-41, or the target
branch of this pull request.

2021-10-25 07:59 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-10-26 16:17 UTC, tmacro approved these changes

2021-10-26 16:58 UTC, miniscruff requested changes

2021-10-26 16:58 UTC, miniscruff commented on lib/utilities/reportHandler.js
> +    const localVolumeCap = process.env.LOCAL_VOLUME_CAPABILITY;
Not a fan of using JSON.parse to get a bool, I would just do a string check with two changes.
```suggestion
    const localVolumeCap = process.env.LOCAL_VOLUME_CAPABILITY || 'true';
```
Default to a true string

2021-10-26 16:58 UTC, miniscruff commented on lib/utilities/reportHandler.js
> +        locationTypeLocal: localVolumeCap === undefined ? true : JSON.parse(localVolumeCap),
No more need to check undefined just compare the string, I always add a toLower/toUpper to prevent some typos
```suggestion
        locationTypeLocal: localVolumeCap.toLowerCase() === 'true',
```

2021-10-26 16:58 UTC, miniscruff commented on tests/unit/management/secureChannel.js
> +    it('should allow configure local file system capability', () => {
I would make this multiple tests, and also test a completely random string value like 'not-a-bool' to determine what happens ( you never know ).

2021-10-26 16:58 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @miniscruff

2021-10-26 23:41 UTC, alexanderchan-scality commented on lib/utilities/reportHandler.js
> +    const localVolumeCap = process.env.LOCAL_VOLUME_CAPABILITY;
can this just be set to a `bool` without the parsing?
also would prefer a specific value vs all truthy

```suggestion
    const localVolumeCap = process.env.LOCAL_VOLUME_CAPABILITY === '1'; // or 'true'
```"

2021-10-27 00:11 UTC, miniscruff commented on lib/utilities/reportHandler.js
> +    const localVolumeCap = process.env.LOCAL_VOLUME_CAPABILITY;
yea but I prefer to be a little more lenient to account for capitals such that 'True' and 'true' are both ok, some people like TRUE or true for values. I know python has a isTruthyVar or something that supports most common true and false values like true, True, 1, yes, y, etc. Could also work. Found it: https://docs.python.org/3/distutils/apiref.html#distutils.util.strtobool

2021-10-27 00:39 UTC, alexanderchan-scality commented on lib/utilities/reportHandler.js
> +    const localVolumeCap = process.env.LOCAL_VOLUME_CAPABILITY;
a truthy set can work too. the specific case I wanted to avoid was '0', which would resolve to true.
~I believe in this project, we are using `0` or `1`~ (it's a mix)

2021-10-27 00:43 UTC, miniscruff commented on lib/utilities/reportHandler.js
> +    const localVolumeCap = process.env.LOCAL_VOLUME_CAPABILITY;
0 would still be false when you take into account my other suggestion of `.toLowerCase() === 'true'`

2021-10-27 17:34 UTC, miniscruff approved these changes

2021-10-27 17:34 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-10-27 22:16 UTC, francoisferrand commented
/approve

2021-10-27 22:16 UTC, bert-e commented
# Build failed



The build for [commit](https://github.com/scality/cloudserver/commit/497188dac587eda969e5ac73ec49075fbbda0849) did not succeed in branch feature/CLDSRV-41.




*The following options are set:* **approve**

2021-10-28 01:13 UTC, rahulreddy commented
/bypass_build_status

2021-10-28 01:13 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.2`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.10`
* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve, bypass_build_status**

2021-10-28 23:39 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.2`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.10`
* `development/7.4`



Please check the status of the associated issue CLDSRV-41.

Goodbye francoisferrand.

2021-10-28 23:39 UTC, merged