Add overall cloudserver status alert
scality/cloudserver pull request #4122
Opened 2021-12-15 15:38 UTC by francoisferrand

Issue: CLDSRV-75

2021-12-15 15:38 UTC, bert-e commented
# Hello francoisferrand,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/cloudserver/bert-e/doc/user).





*Status report is not available.*

2021-12-15 15:38 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-12-15 16:44 UTC, lavigne958 commented on monitoring/alerts.yaml
> +    Expr: sum(up{namespace="${namespace}", service="${service}") * 2 < ${replicas}
wrong syntax... 
you miss the closing `}` at the end of the metric labels

2021-12-16 09:14 UTC, lavigne958 approved these changes

2021-12-16 09:16 UTC, williamlardier approved these changes

2021-12-16 09:21 UTC, williamlardier requested changes
A small formatting issue in the `summary` lines: `summary: "Data Access service is degraded",`

The comma is to be deleted I think!

2021-12-16 09:21 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @williamlardier

2021-12-16 11:22 UTC, williamlardier approved these changes

2021-12-16 11:22 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-12-16 13:07 UTC, lavigne958 commented
/approve

2021-12-16 13:07 UTC, bert-e commented
# Not Author



I'm afraid I cannot do that, @lavigne958:

Only the author of the pull request @francoisferrand can use this command.

Please **delete** the corresponding comment so I can move on.

2021-12-16 13:07 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2021-12-16 13:23 UTC, francoisferrand commented
/approve

2021-12-16 13:23 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.3`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.10`
* `development/7.4`
* `development/8.2`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2021-12-16 13:23 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.3`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.10`
* `development/7.4`
* `development/8.2`



Please check the status of the associated issue CLDSRV-75.

Goodbye francoisferrand.

2021-12-16 13:23 UTC, merged