improvement/CLDSRV-91 Bump Arsenal to 8.1.18
scality/cloudserver pull request #4155
Opened 2022-01-10 17:07 UTC by KillianG

Bump arsenal to 8.1.18 to bring fix for ARTESCA-3109

2022-01-10 17:07 UTC, bert-e commented
# Hello killiang,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://eve.devsca.com/github/scality/cloudserver/bert-e/doc/user).





*Status report is not available.*

2022-01-10 17:07 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue CLDSRV-91 contains:


* `8.2.17`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.3.7`


Please check the `Fix Version/s` of CLDSRV-91, or the target
branch of this pull request.

2022-01-10 17:08 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue CLDSRV-91 contains:


* `8.2.17`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.2.18`

* `8.3.7`


Please check the `Fix Version/s` of CLDSRV-91, or the target
branch of this pull request.

2022-01-10 17:08 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue CLDSRV-91 contains:


* `8.2.18`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.2.18`

* `8.3.7`


Please check the `Fix Version/s` of CLDSRV-91, or the target
branch of this pull request.

2022-01-10 17:11 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue CLDSRV-91 contains:


* `8.2.18`

* `8.3.4`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.2.18`

* `8.3.7`


Please check the `Fix Version/s` of CLDSRV-91, or the target
branch of this pull request.

2022-01-10 17:11 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/CLDSRV-91-bump-arsenal-version` into
`development/8.2`
* [w/8.3/improvement/CLDSRV-91-bump-arsenal-version](https://github.com/scality/cloudserver/compare/development/8.3...w/8.3/improvement/CLDSRV-91-bump-arsenal-version) will be merged into `development/8.3` (pull request #4156)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.10`
* `development/7.4`
* `stabilization/7.4.10`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2022-01-10 17:11 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-01-10 17:22 UTC, miniscruff commented
You will need to run `yarn` to update the package lock as well

2022-01-11 08:22 UTC, bert-e commented
# Conflict




A conflict has been raised during the update of
integration branch `w/8.3/improvement/CLDSRV-91-bump-arsenal-version` with contents from `improvement/CLDSRV-91-bump-arsenal-version`
and `development/8.3`.

Please resolve the conflict on **the integration branch** (`w/8.3/improvement/CLDSRV-91-bump-arsenal-version`).


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout w/8.3/improvement/CLDSRV-91-bump-arsenal-version
 $ git pull  # or "git reset --hard origin/w/8.3/improvement/CLDSRV-91-bump-arsenal-version"
 $ git merge origin/development/8.3
 $ # <intense conflict resolution>
 $ git commit
 $ git merge origin/improvement/CLDSRV-91-bump-arsenal-version
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.3/improvement/CLDSRV-91-bump-arsenal-version
```

2022-01-11 08:26 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-01-11 08:46 UTC, ghost commented
I think the ticket is CLDSRV-92, not CLDSRV-91 :slightly_smiling_face: 

Edit: 91 exisits, so I  updated the other ticket name to make it clearer

Edit 2: We shouldn't have any changes in the 8.3 integration branch, do you know why we have two new packages in the yarn lock file?

2022-01-11 08:48 UTC, williamlardier approved these changes

2022-01-11 08:50 UTC, KillianG commented
> I think the ticket is [CLDSRV-92](https://scality.atlassian.net/browse/CLDSRV-92), not [CLDSRV-91](https://scality.atlassian.net/browse/CLDSRV-91) slightly_smiling_face
> 
> Edit: 91 exisits, so I updated the other ticket name to make it clearer

91 is the bump and 92 is the release

2022-01-11 08:55 UTC, KillianG commented
> Edit 2: We shouldn't have any changes in the 8.3 integration branch, do you know why we have two new packages in the yarn lock file?

I don't know.. this arsenal version is the same that is already used in 8.3 there shouldnt be any changes in lock but there is..

2022-01-11 08:55 UTC, williamlardier commented
Looking at the dev/8.2 branch, can we bump package.json version in this PR directly? The current version is 8.2.17 and we want to release in 8.2.18

2022-01-11 09:03 UTC, bert-e commented
# Conflict




A conflict has been raised during the update of
integration branch `w/8.3/improvement/CLDSRV-91-bump-arsenal-version` with contents from `improvement/CLDSRV-91-bump-arsenal-version`
and `development/8.3`.

Please resolve the conflict on **the integration branch** (`w/8.3/improvement/CLDSRV-91-bump-arsenal-version`).


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout w/8.3/improvement/CLDSRV-91-bump-arsenal-version
 $ git pull  # or "git reset --hard origin/w/8.3/improvement/CLDSRV-91-bump-arsenal-version"
 $ git merge origin/development/8.3
 $ # <intense conflict resolution>
 $ git commit
 $ git merge origin/improvement/CLDSRV-91-bump-arsenal-version
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.3/improvement/CLDSRV-91-bump-arsenal-version
```

2022-01-11 09:23 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-01-11 09:27 UTC, Kerkesni approved these changes
LGTM

2022-01-11 09:44 UTC, jbertran requested changes
Can you investigate that weird version switch? I might be missing something in these dependencies.

2022-01-11 09:44 UTC, jbertran commented on yarn.lock
> +    werelogs scality/werelogs#8.1.0
Same concern here - we somehow went from that same commit to 8.1.0? But 8.1.0 is 2 years ahead time-wise

```
git show tags/8.1.0

tag 8.1.0
Tagger: Rahul Padigela <rahul.padigela@scality.com>
Date:   Fri Apr 9 17:02:24 2021 -0700

v8.1.0

commit e8f8287 (tag: 8.1.0)
Author: Rahul Padigela <rahul.padigela@scality.com>
Date:   Fri Apr 9 17:02:23 2021 -0700

    v8.1.0
```

2022-01-11 09:44 UTC, jbertran commented on yarn.lock
> +    werelogs scality/werelogs#351a2a3
I'm concerned here - we've pinned a commit that is *NOT* a tag. I'm not sure how that happened, it looks like we made a weird release.

```
git show 351a2a3

commit 351a2a3
Merge: 1a6e052 4e0d97c
Author: Katherine Laue <Katherine.laue@wustl.edu>
Date:   Fri Jun 28 14:03:48 2019 -0700

    Merge remote-tracking branch 'origin/w/7.5/improvement/S3C-2292-upgrade-nodejs' into w/8.0/improvement/S3C-2292-upgrade-nodejs
```

2022-01-11 09:44 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @jbertran

2022-01-11 10:39 UTC, bert-e commented
# History mismatch



Merge commit #37d0260e0b1c063c9c4da1be769eeb2832da08e5 on the integration branch
`w/8.3/improvement/CLDSRV-91-bump-arsenal-version` is merging a branch which is neither the current
branch `improvement/CLDSRV-91-bump-arsenal-version` nor the development branch
`development/8.3`.

It is likely due to a rebase of the branch `improvement/CLDSRV-91-bump-arsenal-version` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2022-01-11 10:39 UTC, KillianG commented
/reset

2022-01-11 10:40 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2022-01-11 10:40 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/CLDSRV-91-bump-arsenal-version` into
`development/8.2`
* [w/8.3/improvement/CLDSRV-91-bump-arsenal-version](https://github.com/scality/cloudserver/compare/development/8.3...w/8.3/improvement/CLDSRV-91-bump-arsenal-version) will be merged into `development/8.3` (pull request #4158)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.10`
* `development/7.4`
* `stabilization/7.4.10`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2022-01-11 10:40 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @jbertran

2022-01-11 10:41 UTC, jbertran approved these changes

2022-01-11 10:41 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-01-11 10:42 UTC, KillianG commented
werelogs problem was due to the waterflow because someone bumped sproxyd version in v7.4 and waterflow updated 8.2 as well with the old version of werelogs

2022-01-11 10:43 UTC, bert-e commented
# Conflict




A conflict has been raised during the update of
integration branch `w/8.3/improvement/CLDSRV-91-bump-arsenal-version` with contents from `improvement/CLDSRV-91-bump-arsenal-version`
and `development/8.3`.

Please resolve the conflict on **the integration branch** (`w/8.3/improvement/CLDSRV-91-bump-arsenal-version`).


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout w/8.3/improvement/CLDSRV-91-bump-arsenal-version
 $ git pull  # or "git reset --hard origin/w/8.3/improvement/CLDSRV-91-bump-arsenal-version"
 $ git merge origin/development/8.3
 $ # <intense conflict resolution>
 $ git commit
 $ git merge origin/improvement/CLDSRV-91-bump-arsenal-version
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.3/improvement/CLDSRV-91-bump-arsenal-version
```

2022-01-11 10:46 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-01-11 14:20 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue CLDSRV-91 contains:


* `8.2.19`

* `8.3.7`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.2.18`

* `8.3.7`


Please check the `Fix Version/s` of CLDSRV-91, or the target
branch of this pull request.

2022-01-11 14:21 UTC, bert-e commented
# History mismatch



Merge commit #17922559602a0881b740239de2be2c72320f2b03 on the integration branch
`w/8.3/improvement/CLDSRV-91-bump-arsenal-version` is merging a branch which is neither the current
branch `improvement/CLDSRV-91-bump-arsenal-version` nor the development branch
`development/8.3`.

It is likely due to a rebase of the branch `improvement/CLDSRV-91-bump-arsenal-version` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2022-01-11 14:21 UTC, KillianG commented
/reset

2022-01-11 14:21 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2022-01-11 14:21 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.3/improvement/CLDSRV-91-bump-arsenal-version` with contents from `improvement/CLDSRV-91-bump-arsenal-version`
and `development/8.3`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.3/improvement/CLDSRV-91-bump-arsenal-version origin/development/8.3
 $ git merge origin/improvement/CLDSRV-91-bump-arsenal-version
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.3/improvement/CLDSRV-91-bump-arsenal-version
```

2022-01-11 14:33 UTC, bert-e commented
# History mismatch



Merge commit #3603abc0b989763fa7d341cda6029e69b7fc25b6 on the integration branch
`w/8.3/improvement/CLDSRV-91-bump-arsenal-version` is merging a branch which is neither the current
branch `improvement/CLDSRV-91-bump-arsenal-version` nor the development branch
`development/8.3`.

It is likely due to a rebase of the branch `improvement/CLDSRV-91-bump-arsenal-version` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2022-01-11 14:33 UTC, KillianG commented
/reset

2022-01-11 14:33 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2022-01-11 14:33 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.3/improvement/CLDSRV-91-bump-arsenal-version` with contents from `improvement/CLDSRV-91-bump-arsenal-version`
and `development/8.3`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.3/improvement/CLDSRV-91-bump-arsenal-version origin/development/8.3
 $ git merge origin/improvement/CLDSRV-91-bump-arsenal-version
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.3/improvement/CLDSRV-91-bump-arsenal-version
```

2022-01-11 14:50 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/CLDSRV-91-bump-arsenal-version` into
`development/8.2`
* [w/8.3/improvement/CLDSRV-91-bump-arsenal-version](https://github.com/scality/cloudserver/compare/development/8.3...w/8.3/improvement/CLDSRV-91-bump-arsenal-version) will be merged into `development/8.3` (pull request #4160)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.10`
* `development/7.4`
* `stabilization/7.4.10`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2022-01-11 14:50 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-01-11 15:41 UTC, bert-e commented
# History mismatch



Merge commit #b3bab7a78d8664d995d2f0e4c88adbb6d501f5f7 on the integration branch
`w/8.3/improvement/CLDSRV-91-bump-arsenal-version` is merging a branch which is neither the current
branch `improvement/CLDSRV-91-bump-arsenal-version` nor the development branch
`development/8.3`.

It is likely due to a rebase of the branch `improvement/CLDSRV-91-bump-arsenal-version` and the
merge is not possible until all related `w/*` branches are deleted or updated.

**Please use the `reset` command to have me reinitialize these branches.**

2022-01-11 15:41 UTC, KillianG commented
/reset

2022-01-11 15:41 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.

2022-01-11 15:42 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.3/improvement/CLDSRV-91-bump-arsenal-version` with contents from `improvement/CLDSRV-91-bump-arsenal-version`
and `development/8.3`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.3/improvement/CLDSRV-91-bump-arsenal-version origin/development/8.3
 $ git merge origin/improvement/CLDSRV-91-bump-arsenal-version
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.3/improvement/CLDSRV-91-bump-arsenal-version
```

2022-01-11 15:59 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/CLDSRV-91-bump-arsenal-version` into
`development/8.2`
* [w/8.3/improvement/CLDSRV-91-bump-arsenal-version](https://github.com/scality/cloudserver/compare/development/8.3...w/8.3/improvement/CLDSRV-91-bump-arsenal-version) will be merged into `development/8.3` (pull request #4161)



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.10`
* `development/7.4`
* `stabilization/7.4.10`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.

2022-01-11 15:59 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers

2022-01-11 16:12 UTC, KillianG commented
/approve

2022-01-11 16:12 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue CLDSRV-91 contains:


* `8.2.18`

* `8.3.7`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `8.2.19`

* `8.3.7`


Please check the `Fix Version/s` of CLDSRV-91, or the target
branch of this pull request.




*The following options are set:* **approve**

2022-01-11 16:13 UTC, bert-e commented
# Queue out of order



The changeset has received all authorizations to enter the merge queue,
however the merge queue is currently in an incoherent state. In order
to protect this pull-request, I have not added the changeset to the
queue.

Please contact a member of release engineering.





*The following options are set:* **approve**

2022-01-11 17:24 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/8.2`

* :heavy_check_mark: `development/8.3`



The following branches will **NOT** be impacted:

* `development/6.4`
* `development/7.10`
* `development/7.4`
* `stabilization/7.4.10`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve**

2022-01-11 17:24 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/8.2`

* :heavy_check_mark: `development/8.3`



The following branches have **NOT** changed:

* `development/6.4`
* `development/7.10`
* `development/7.4`
* `stabilization/7.4.10`



Please check the status of the associated issue CLDSRV-91.

Goodbye killiang.

2022-01-11 17:24 UTC, merged