CLDSRV-451: updating buckettagging apis for impDeny
scality/cloudserver pull request #5495
Opened 2023-12-14 13:22 UTC by benzekrimaha

2023-12-14 13:22 UTC, bert-e commented
# Hello benzekrimaha,



My role is to assist you with the merge of this
pull request. Please type `@bert-e help` to get information
on this process, or consult the [user documentation](
https://bert-e.scality.net/scality/cloudserver/doc/user).





*Status report is not available.*

2023-12-14 13:22 UTC, bert-e commented
# Incorrect fix version



The `Fix Version/s` in issue CLDSRV-451 contains:


* `7.70.11.3`



Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:



* `7.70.36`

* `8.6.17`

* `8.7.37`

* `8.8.11`


Please check the `Fix Version/s` of CLDSRV-451, or the target
branch of this pull request.

2023-12-14 13:23 UTC, benzekrimaha commented
ping

2023-12-14 13:23 UTC, bert-e commented
# Request integration branches



Waiting for integration branch creation to be requested by the user.

To request integration branches, please comment on this pull request with the following command:

```
/create_integration_branches
```

Alternatively, the `/approve` and `/create_pull_requests` commands will automatically
create the integration branches.

2023-12-14 13:26 UTC, benzekrimaha commented
/create_integration_branches

2023-12-14 13:26 UTC, benzekrimaha commented
/wait

2023-12-14 13:26 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update` with contents from `improvement/CLDSRV-451-specific-7.70-apis-update`
and `development/8.6`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update origin/development/8.6
 $ git merge origin/improvement/CLDSRV-451-specific-7.70-apis-update
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update
```





*The following options are set:* **create_integration_branches**

2023-12-14 13:30 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update` with contents from `improvement/CLDSRV-451-specific-7.70-apis-update`
and `development/8.6`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update origin/development/8.6
 $ git merge origin/improvement/CLDSRV-451-specific-7.70-apis-update
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update
```





*The following options are set:* **create_integration_branches**

2023-12-14 13:30 UTC, bert-e commented
# Request integration branches



Waiting for integration branch creation to be requested by the user.

To request integration branches, please comment on this pull request with the following command:

```
/create_integration_branches
```

Alternatively, the `/approve` and `/create_pull_requests` commands will automatically
create the integration branches.

2023-12-14 15:59 UTC, benzekrimaha commented
/create_integration_branches

2023-12-14 15:59 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update` with contents from `improvement/CLDSRV-451-specific-7.70-apis-update`
and `development/8.6`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update origin/development/8.6
 $ git merge origin/improvement/CLDSRV-451-specific-7.70-apis-update
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update
```





*The following options are set:* **create_integration_branches**

2023-12-14 16:04 UTC, benzekrimaha commented
ping

2023-12-14 16:05 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.7/improvement/CLDSRV-451-specific-7.70-apis-update` with contents from `w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update`
and `development/8.7`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.7/improvement/CLDSRV-451-specific-7.70-apis-update origin/development/8.7
 $ git merge origin/w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.7/improvement/CLDSRV-451-specific-7.70-apis-update
```





*The following options are set:* **create_integration_branches**

2023-12-14 16:11 UTC, benzekrimaha commented
ping

2023-12-14 16:11 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.8/improvement/CLDSRV-451-specific-7.70-apis-update` with contents from `w/8.7/improvement/CLDSRV-451-specific-7.70-apis-update`
and `development/8.8`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.8/improvement/CLDSRV-451-specific-7.70-apis-update origin/development/8.8
 $ git merge origin/w/8.7/improvement/CLDSRV-451-specific-7.70-apis-update
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.8/improvement/CLDSRV-451-specific-7.70-apis-update
```





*The following options are set:* **create_integration_branches**

2023-12-14 16:17 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers











*The following options are set:* **create_integration_branches**

2023-12-14 16:22 UTC, benzekrimaha commented
/reset

2023-12-14 16:22 UTC, bert-e commented
# Lossy reset warning



There seems to be *manual* commits on integration branches (e.g. conflict
resolutions) that will be lost if you chose to *reset*.

**You can use the `force_reset` command if you still want me
to delete those branches.**





*The following options are set:* **create_integration_branches**

2023-12-14 16:22 UTC, benzekrimaha commented
@bert-e force_reset

2023-12-14 16:22 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers











*The following options are set:* **create_integration_branches**

2023-12-14 16:23 UTC, benzekrimaha commented
@bert-e  force_reset

2023-12-14 16:23 UTC, bert-e commented
# Reset complete



I have successfully deleted this pull request's integration branches.






*The following options are set:* **create_integration_branches**

2023-12-14 16:23 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update` with contents from `improvement/CLDSRV-451-specific-7.70-apis-update`
and `development/8.6`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update origin/development/8.6
 $ git merge origin/improvement/CLDSRV-451-specific-7.70-apis-update
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update
```





*The following options are set:* **create_integration_branches**

2023-12-14 16:23 UTC, benzekrimaha commented
/create_integration_branches

2023-12-14 16:30 UTC, benzekrimaha commented
ping

2023-12-14 16:30 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.7/improvement/CLDSRV-451-specific-7.70-apis-update` with contents from `w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update`
and `development/8.7`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.7/improvement/CLDSRV-451-specific-7.70-apis-update origin/development/8.7
 $ git merge origin/w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.7/improvement/CLDSRV-451-specific-7.70-apis-update
```





*The following options are set:* **create_integration_branches**

2023-12-14 16:33 UTC, benzekrimaha commented
ping

2023-12-14 16:34 UTC, bert-e commented
# Conflict




A conflict has been raised during the creation of
integration branch `w/8.8/improvement/CLDSRV-451-specific-7.70-apis-update` with contents from `w/8.7/improvement/CLDSRV-451-specific-7.70-apis-update`
and `development/8.8`.

**I have not created the integration branch.**


Here are the steps to resolve this conflict:

```bash
 $ git fetch
 $ git checkout -B w/8.8/improvement/CLDSRV-451-specific-7.70-apis-update origin/development/8.8
 $ git merge origin/w/8.7/improvement/CLDSRV-451-specific-7.70-apis-update
 $ # <intense conflict resolution>
 $ git commit
 $ git push -u origin w/8.8/improvement/CLDSRV-451-specific-7.70-apis-update
```





*The following options are set:* **create_integration_branches**

2023-12-14 16:38 UTC, benzekrimaha commented
ping

2023-12-14 16:38 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers











*The following options are set:* **create_integration_branches**

2023-12-14 16:39 UTC, benzekrimaha commented
/create_pull_requests

2023-12-14 16:39 UTC, bert-e commented
# Integration data created



I have created the integration data for the additional destination branches.

* this pull request will merge `improvement/CLDSRV-451-specific-7.70-apis-update` into
`development/7.70`
* [w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update](https://github.com/scality/cloudserver/compare/development/8.6...w/8.6/improvement/CLDSRV-451-specific-7.70-apis-update) will be merged into `development/8.6` (pull request #5496)
* [w/8.7/improvement/CLDSRV-451-specific-7.70-apis-update](https://github.com/scality/cloudserver/compare/development/8.7...w/8.7/improvement/CLDSRV-451-specific-7.70-apis-update) will be merged into `development/8.7` (pull request #5497)
* [w/8.8/improvement/CLDSRV-451-specific-7.70-apis-update](https://github.com/scality/cloudserver/compare/development/8.8...w/8.8/improvement/CLDSRV-451-specific-7.70-apis-update) will be merged into `development/8.8` (pull request #5498)



The following branches will **NOT** be impacted:

* `development/7.10`
* `development/7.4`




*Follow* integration pull requests if you would like to be notified of
build statuses by email.







*The following options are set:* **create_pull_requests, create_integration_branches**

2023-12-14 16:39 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers











*The following options are set:* **create_pull_requests, create_integration_branches**

2023-12-14 16:41 UTC, anurag4DSB approved these changes
reveiwed integration branch https://github.com/scality/cloudserver/pull/5497#pullrequestreview-1782227448
there are new changes in the merge commit for metadataSearch, object Restore and routeveeam

2023-12-14 16:41 UTC, anurag4DSB commented
Integration tests used: https://github.com/scality/cloudserver/pull/5496

2023-12-14 16:45 UTC, KazToozs approved these changes

2023-12-14 16:49 UTC, anurag4DSB requested changes, later dismissed
adding a blocker for merge as author will be OOO tomorrow

2023-12-14 16:49 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers






The following reviewers are expecting changes from the author, or must review again:

* @anurag4dsb







*The following options are set:* **create_pull_requests, create_integration_branches**

2023-12-14 17:27 UTC, anurag4DSB approved these changes

2023-12-14 17:27 UTC, bert-e commented
# Waiting for approval



The following approvals are needed before I can proceed with the merge:


* the author


* 2 peers











*The following options are set:* **create_pull_requests, create_integration_branches**

2023-12-14 17:53 UTC, anurag4DSB approved these changes

2023-12-15 06:35 UTC, benzekrimaha commented
ping

2023-12-15 06:43 UTC, benzekrimaha commented
@bert-e  approve

2023-12-15 06:44 UTC, bert-e commented
# In the queue



The changeset has received all authorizations and has been added to the
relevant queue(s). The queue(s) will be merged in the target development
branch(es) as soon as builds have passed.

The changeset will be merged in:


* :heavy_check_mark: `development/7.70`

* :heavy_check_mark: `development/8.6`

* :heavy_check_mark: `development/8.7`

* :heavy_check_mark: `development/8.8`



The following branches will **NOT** be impacted:

* `development/7.10`
* `development/7.4`



There is no action required on your side. You will be notified here once
the changeset has been merged. In the unlikely event that the changeset
fails permanently on the queue, a member of the admin team will
contact you to help resolve the matter.

*IMPORTANT*

Please do not attempt to modify this pull request.

* Any commit you add on the source branch will trigger a new cycle after the
  current queue is merged.
* Any commit you add on one of the integration branches will be **lost**.

If you need this pull request to be removed from the queue, please contact a
member of the admin team now.




*The following options are set:* **approve, create_pull_requests, create_integration_branches**

2023-12-15 07:02 UTC, bert-e commented
# 


I have successfully merged the changeset of this pull request
into targetted development branches:


* :heavy_check_mark: `development/7.70`

* :heavy_check_mark: `development/8.6`

* :heavy_check_mark: `development/8.7`

* :heavy_check_mark: `development/8.8`



The following branches have **NOT** changed:

* `development/7.10`
* `development/7.4`



Please check the status of the associated issue CLDSRV-451.

Goodbye benzekrimaha.

2023-12-15 07:02 UTC, merged